### PR TITLE
make acceptanceTests happen in parallel to assemble to catch mistakes early and speed up build

### PR DESCRIPTION
**Pull request by RatanRSur**
I pulled the ATs down to the base level here while leaving the others dependent on assemble because it would reduce the build time. This will be especially important now that the new changes to the ATs make them take significantly longer.

### CODE REVIEW

**Comment by CjHare** [comment]
Interesting, the AT still look to have dependencies on the Besu code. Does removing the dependency open up build Besu twice (once triggered by assemble, then again be AT)?

From a purely logic viewpoint, why begin tests (acceptance or otherwise) before you know the code builds successfully?

**Comment by RatanRSur** [comment]
It's a tradeoff, do we want to optimize for no unnecessary work by the machines or faster builds? I lean towards faster builds as the cost in redundancy is probably worth it for the time savings for developers.

**Comment by ajsutton** [comment]
The build is very deliberately setup with everything building once up front and then later jobs testing those binaries.  Then you know the binaries you ship and the exact same bytes as the ones you tested.

But also, if you wind up doing pretty much all of what assemble does in each task it winds up taking pretty much the same time anyway.  We can make ATs go faster by spreading them across more boxes.

**Comment by RatanRSur** [comment]
Ahh, I thought we just rebuilt them anyways. I missed that we have the `Restore Gradle Dependencies` step.

**Pull request closed without merging**
