### PR TITLE
Change map key in eth peers

### PR DESCRIPTION
**Pull request by pinges**
Trying to fix multiple connections to the same peer by using the peer id as the key to the map

### CODE REVIEW

**Comment by helderjnpinto** [comment]
@pinges hey all good ? when this PR will be fixed and merged, any time estimation? I have in my network one peer duplicated 1088 times :).

**Review by jflo — APPROVED** [review]
Other than the aesthetics mentioned in my comment, this is good.

**Comment by macfarla** [comment]
@pinges are you closing this PR in favour of your new approach?

**Comment by macfarla** [comment]
Closing this in favour of a new approach cc @pinges

**Pull request closed without merging**
