### PR TITLE
re-default global max rpc batch size to 1k

### PR DESCRIPTION
**Pull request by garyschulte**
## PR description
default global rpc max batch size to 1000 for 23.1.0, revisit in 23.1.1

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Acceptance Tests (Non Mainnet)

- [ ] I have considered running `./gradlew acceptanceTestNonMainnet` locally if my PR affects non-mainnet modules.

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by gfukushima — APPROVED** [review]
lgtm

**Review by siladu — APPROVED** [review]
LGTM

**Comment by siladu** [comment]
@garyschulte Why did the ref tests change?

**Comment by garyschulte** [comment]
> @garyschulte Why did the ref tests change?

overzealous git add picked up the execution-spec-test artifacts, fixed

**Review by siladu — APPROVED** [review]
Looks even better ;)

**Review by gfukushima — APPROVED** [review]

**Pull request merged**
