### PR TITLE
Flat db heal - deprecate CLI option and set to always true

### PR DESCRIPTION
**Pull request by macfarla**
* set flat db healing enabled to true always
* remove duplicate setup of default values from Sync Options class

refs #6157

### CODE REVIEW

**Review by pinges — APPROVED** [review]
LGTM and nice cleanup as well!

**Comment by macfarla** [comment]
will wait for feedback from @garyschulte

**Comment by garyschulte** [comment]
This LGTM, but there are a couple criteria of #6157 it doesn't meet:
* full sync'd nodes are not getting defaulted to fully flattened DB, see FlatDbStrategyProvider.deriveFlatDbStrategy
* we need to offer a subcommand to "heal" a node's flat db storage so that the user doesn't have to resync the whole worldstate

I think it is reasonable to handle those two in separate PRs.  They are more tricky cases

**Review by garyschulte — APPROVED** [review]
LGTM, comments noted

**Comment by macfarla** [comment]
agree @garyschulte those changes are related but separate, let's do separate PRs

**Pull request merged**
