### PR TITLE
Create a new flag on RocksDB for high spec hardware to boost performance

### PR DESCRIPTION
**Pull request by ahamlat**
Signed-off-by: Ameziane H <ameziane.hamlat@consensys.net>

## PR description
Create a new flag on RocksDB (_--Xplugin-rocksdb-high-spec-enabled_) for high spec hardware to boost performance. 
With this first version, the impact is on memory usage, as we're tuning RocksDB block cache and Memtables size. By high spec here, we mean a VM or machine with more than 16 GiB. Other modifications in future may include other resources' requirements but for now, the only requirement is on RAM.

The results are promising on a 32 GiB AWS VM, as this new flag reduces 95 percentile block processing time by 30%.
image

Performance improvements may appear in a couple of hours because of cache warm up time, as we can notice with RocksDB block cache hit ratio and RocksDB get time :

image
image

 
## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by jflo — APPROVED** [review]

**Comment by milesthedisch** [comment]
Minimum hardware requirements to run this flag?

**Comment by ahamlat** [comment]
I just update the description @milesthedisch, you must have at least 16 GiB RAM.

**Comment by garyschulte** [comment]
> Minimum hardware requirements to run this flag?

This is mostly a high spec memory requirement.  besu will consume up to an additional 2gb of ram with this enabled.  16gb machine is the recommended minimum for a machine running just an EL/CL combo

**Comment by garyschulte** [comment]
burned in on mainnet along with 4417 and 4425

**Pull request merged**
