### PR TITLE
add rlp decode subcommand

### PR DESCRIPTION
**Pull request by Brindrajsinh-Chauhan**
## Fixed Issue(s)

Adds `decode` subcommand to rlp based on this [Issue](https://github.com/hyperledger/besu/issues/3074)

Example
```
besu rlp decode --from=<input-file> --to=<output-file> --type=<IBFT_EXTRA_DATA|QBFT_EXTRA_DATA>
```

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by macfarla — COMMENTED** [review]
@Brindrajsinh-Chauhan the subcommand looks pretty straightforward - can you add some tests? There's some examples in the codebase already - especially around error conditions - eg what happens if you specify a file path that doesn't exist

**Comment by Brindrajsinh-Chauhan** [comment]
sounds good, will add tests around it and update the PR. Thank you so much for the feedback

**Comment by Brindrajsinh-Chauhan** [comment]
@macfarla Updated the PR with tests. Would be grateful if you could give it a look. The tests might need approval to run and build. Thank you

**Review by macfarla — APPROVED** [review]

**Comment by macfarla** [comment]
looks good @Brindrajsinh-Chauhan - thanks for your contribution!

May be helpful for docs - some local testing I did that shows more usage options

```
➜  b2 git:(rlp-decode) ✗ echo 0xf853a00000000000000000000000000000000000000000000000000000000000000000ea94be068f726a13c8d46c44be6ce9d275600e1735a4945ff6f4b66a46a2b2310a6f3a93aaddc0d9a1c193808400000000c0 > a.txt
besu rlp decode --from=a.txt --to=b.txt --type=IBFT_EXTRA_DATA
➜  b2 git:(rlp-decode) ✗ less b.txt
➜  b2 git:(rlp-decode) ✗ besu rlp decode --from=a.txt --type=IBFT_EXTRA_DATA
[0xbe068f726a13c8d46c44be6ce9d275600e1735a4, 0x5ff6f4b66a46a2b2310a6f3a93aaddc0d9a1c193]
➜  b2 git:(rlp-decode) ✗ cat a.txt | besu rlp decode
[0xbe068f726a13c8d46c44be6ce9d275600e1735a4, 0x5ff6f4b66a46a2b2310a6f3a93aaddc0d9a1c193]
➜  b2 git:(rlp-decode) ✗ cat a.txt | besu rlp decode --type=IBFT_EXTRA_DATA
[0xbe068f726a13c8d46c44be6ce9d275600e1735a4, 0x5ff6f4b66a46a2b2310a6f3a93aaddc0d9a1c193]
➜  b2 git:(rlp-decode) ✗ cat a.txt | besu rlp decode --type=QBFT_EXTRA_DATA
org.hyperledger.besu.ethereum.rlp.RLPException: Expected current item to be a list, but it is: SHORT_ELEMENT (at bytes 78-79: ...d9a1c193[80]84000000...)
```

**Comment by Brindrajsinh-Chauhan** [comment]
Thank you @macfarla for the review. Should I open a PR for docs update of is the process something different.

**Comment by macfarla** [comment]
> Thank you @macfarla for the review. Should I open a PR for docs update of is the process something different.

You are welcome to open a PR in the docs repo - some of the linting is a bit fiddly but docs team can definitely help with that to get it over the line! That would be much appreciated!

Otherwise it goes on the (quite long!) backlog for the docs team (based on the label).

Either way, it will expedite things if we can at least draft the content - usage examples and description.

**Comment by Brindrajsinh-Chauhan** [comment]
@macfarla could you please approve the workflow run again, had to merge with main for it to automerge

**Pull request merged**
