### PR TITLE
Add null pointer check and testcase for snapsync tasks

### PR DESCRIPTION
**Pull request by pullurib**
## PR description
Added a null pointer check where a null pointer exception was thrown as described in the issue 
Added a testcase to verify the case is handled gracefully

taskElement shouldn't be null ideally as it's only added to trie after validating proofs and we get to this point after checking if data is available and isValidProof is true.  
- A race condition between calling addResponse(requestDataStep) and getChildRequests(persistDataStep) seems unlikely as they are sequential in pipeline and synchronized by setting isValidProof after adding taskElement and checked before accessing taskElement.  
- Clear() on the request also sets isValidProof to false before removing the element from Trie.

## Fixed Issue(s)
#6113

### CODE REVIEW

**Review by lu-pinto — APPROVED** [review]
LGTM

**Comment by matkt** [comment]
is it something we already had during a sync ?

**Comment by matkt** [comment]
For me, doing this is not a good idea because if we are searching for the children, it is typically because we intend to persist the parent. If there is an error of this type and we return empty, we will persist the request and never search for the child requests again, which will lead to an incomplete tree. I don’t think this is a serious issue because I believe this case doesn’t happen often, but I consider the fix to be invalid.

**Comment by pullurib** [comment]
@matkt Based on my understanding, a null pointer failure should be handled similarly to an invalid proof by adding the task to the retry queue. I noticed that invalid proofs are managed in the addResponse function. Handling a null taskElement by adding it to the retry queue—much like adding it to the healing list—seems appropriate. Please let me know if this approach makes sense. I will look into this further and follow up with a fix.

**Comment by matkt** [comment]
In your case, the response is marked as received because the proof is valid. If the request is therefore marked as valid, we will not retry it, and we will not fetch the subsequent requests to complete the range (see https://github.com/pullurib/besu/blob/9ea174bd1c2de13709f2e1168af10272b606269a/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/request/StorageRangeDataRequest.java#L160 and https://github.com/pullurib/besu/blob/9ea174bd1c2de13709f2e1168af10272b606269a/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/CompleteTaskStep.java#L50).

In the case where the proof is invalid, it will be marked as false, and CompleteTaskStep will put it back into the pipeline.

**Pull request merged**
