### PR TITLE
Remove deprecated EF bootnodes

### PR DESCRIPTION
**Pull request by skylenet**
## PR description

Removed some deprecated EF bootnodes. The same nodes have been removed on geth: https://github.com/ethereum/go-ethereum/pull/26828 

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Acceptance Tests (Non Mainnet)

- [ ] I have considered running `./gradlew acceptanceTestNonMainnet` locally if my PR affects non-mainnet modules.

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by gfukushima** [comment]
@skylenet hope you don't mind, I added a small clean up to some of those json used for tests only. Thanks for sending pull request.

**Review by shemnon — COMMENTED** [review]
LGTM

**Comment by siladu** [comment]
@skylenet Could this have an impact on peering abilities for the regions affected?

**Review by atoulme — APPROVED** [review]

**Comment by skylenet** [comment]
> @skylenet Could this have an impact on peering abilities for the regions affected?

Not really as there's also the DNS discovery approach that should be preferred.

**Pull request merged**
