### PR TITLE
Add ETC Spiral EVM configuration

### PR DESCRIPTION
**Pull request by diega**
## PR description
During the last ETC network upgrade, Besu nodes got stalled because, inadvertently, [EIP-4399](https://eips.ethereum.org/EIPS/eip-4399) was _included_ instead of _omitted_.

For the future, we'll also test omissions to the protocol and not only additions.

### CODE REVIEW

**Review by shemnon — APPROVED** [review]
Is there a need for full fluent API support for classic forks?

**Comment by diega** [comment]
@shemnon I think _ProtocolSpecs_ fluency is pretty good, is that fluent API the one that you mean?

**Comment by shemnon** [comment]
APIs from this directory - https://github.com/hyperledger/besu/blob/d7e5b261141da6cbb4a8131ed2feb1603e3e68f8/evm/src/main/java/org/hyperledger/besu/evm/fluent

Guido has a fuzzer he uses there.  But I'm not sure it would have caught the DIFFICULTY/RANDAO swap, even against core-geth.

**Comment by diega** [comment]
That sounds really interesting, do you know where I can find some documentation on how to run the [fuzzer](https://github.com/guidovranken/cryptofuzz) with Besu's EVM?

**Review by macfarla — COMMENTED** [review]
this could use a changelog entry

**Review by fab-10 — COMMENTED** [review]
CI Publish job is failing due to a missing javadoc

```
> Task :evm:javadoc
/home/circleci/project/evm/src/main/java/org/hyperledger/besu/evm/ClassicEVMs.java:29: warning: no comment
public class ClassicEVMs {
       ^
```

**Pull request merged**
