### PR TITLE
Fix for #3786 OOM on trace_block and trace_replayBlockTransactions RPC methods (fix dco dhallatmaine)

### PR DESCRIPTION
**Pull request by Gabriel-Trintinalia**
fix dco for https://github.com/hyperledger/besu/pull/5029 @dhallatmaine 

## PR description
This change addresses a situation where all TraceFrame's for all Transactions in a block are loaded into memory, when only the TraceFrame's for a single Transaction are ever needed.

## Fixed Issue(s)
fixes https://github.com/hyperledger/besu/issues/3786

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Acceptance Tests (Non Mainnet)

- [x] I have considered running `./gradlew acceptanceTestNonMainnet` locally if my PR affects non-mainnet modules.

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by macfarla — APPROVED** [review]
LGTM 
@daniellehrner @ahamlat are there specific tests you want to run on this?

**Comment by ahamlat** [comment]
I was able to reproduce without this PR the OOM error, by starting Besu with -Xmx3g and running trace_replayBlockTransactions on block 16627443 on mainnet.
```a42dfc8c38af27e45a9206645ea9c1197ea) in 0.327s. Peers: 25","throwable":""}
{"@timestamp":"2023-02-14T15:44:15,731","level":"INFO","thread":"vert.x-worker-thread-0","class":"AbstractEngineNewPayload","message":"Imported #16,627,962 / 186 tx / base fee 31.94 gwei / 16,956,329 (56.5%) gas / (0x065c993d09265a30a4639607532271925f015622823aafd31f99cd3d8de70c59) in 3.739s. Peers: 25","throwable":""}
{"@timestamp":"2023-02-14T15:44:26,837","level":"INFO","thread":"vert.x-worker-thread-0","class":"AbstractEngineNewPayload","message":"Imported #16,627,963 / 136 tx / base fee 32.46 gwei / 16,440,973 (54.8%) gas / (0x26433d35d0d0bc21a64d09171d6c1279d393c3ccc4a9f6e4c775d9b620e11921) in 1.128s. Peers: 25","throwable":""}
{"@timestamp":"2023-02-14T15:44:49,872","level":"WARN","thread":"vertx-blocked-thread-checker","class":"BlockedThreadChecker","message":"Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2541 ms, time limit is 2000 ms","throwable":""}
{"@timestamp":"2023-02-14T15:45:13,258","level":"ERROR","thread":"nioEventLoopGroup-3-10","class":"DeFramer","message":"Exception while processing incoming message","throwable":" java.lang.OutOfMemoryError: Java heap space\n"}
{"@timestamp":"2023-02-14T15:45:15,405","level":"WARN","thread":"vert.x-acceptor-thread-0","class":"DefaultChannelPipeline","message":"An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.","throwable":" java.lang.OutOfMemoryError: Java heap space\n\tat io.netty.channel.epoll.EpollServerSocketChannel.newChildChannel(EpollServerSocketChannel.java:102)\n\tat io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:120)\n\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:375)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n"}
{"@timestamp":"2023-02-14T15:45:18,171","level":"WARN","thread":"vertx-blocked-thread-checker","class":"BlockedThreadChecker","message":"Thread Thread[vert.x-worker-thread-17,5,main] has been blocked for 65281 ms, time limit is 60000 ms","throwable":" io.vertx.core.VertxException: Thread blocked\n\tat app//org.apache.tuweni.bytes.MutableBytes32.create(MutableBytes32.java:28)\n\tat app//org.apache.tuweni.bytes.Bytes32.leftPad(Bytes32.java:187)\n\tat app//org.hyperledger.besu.ethereum.vm.DebugOperationTracer.captureStack(DebugOperationTracer.java:229)\n\tat app//org.hyperledger.besu.ethereum.vm.DebugOperationTracer.tracePostExecution(DebugOperationTracer.java:73)\n\tat app//org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:330)\n\tat app//org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:174)\n\tat app//org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:192)\n\tat app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:495)\n\tat app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:405)\n\tat app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:204)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.lambda$prepareReplayAction$0(BlockTracer.java:60)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer$$Lambda$2216/0x00000008013a9d60.performAction(Unknown Source)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$0(BlockReplay.java:60)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay$$Lambda$2222/0x00000008013aac98.apply(Unknown Source)\n\tat java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base@17.0.5/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)\n\tat java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$1(BlockReplay.java:66)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay$$Lambda$2217/0x00000008013aa188.perform(Unknown Source)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.performActionWithBlock(BlockReplay.java:163)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.block(BlockReplay.java:52)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.trace(BlockTracer.java:45)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.traceBlock(TraceReplayBlockTransactions.java:118)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.lambda$resultByBlockNumber$0(TraceReplayBlockTransactions.java:102)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions$$Lambda$2215/0x00000008013a9248.apply(Unknown Source)\n\tat java.base@17.0.5/java.util.Optional.map(Optional.java:260)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.resultByBlockNumber(TraceReplayBlockTransactions.java:102)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.findResultByParamType(AbstractBlockParameterMethod.java:88)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.response(AbstractBlockParameterMethod.java:102)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:42)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:41)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.executeRequest(JsonRpcExecutorHandler.java:118)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.executeJsonObjectRequest(JsonRpcExecutorHandler.java:131)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:78)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler$$Lambda$1222/0x00000008011c2280.handle(Unknown Source)\n\tat app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)\n\tat app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$1548/0x00000008012a8ac0.handle(Unknown Source)\n\tat app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)\n\tat app//io.vertx.core.impl.ContextImpl$$Lambda$1442/0x0000000801244438.handle(Unknown Source)\n\tat app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)\n\tat app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)\n\tat app//io.vertx.core.impl.ContextImpl$$Lambda$1438/0x0000000801243980.run(Unknown Source)\n\tat java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base@17.0.5/java.lang.Thread.run(Thread.java:833)\n"}
```
By installing this PR and running the same test (starting Besu with -Xmx3g and running trace_replayBlockTransactions on block 16627443 on mainnet), I haven't had the error with several tests. I can confirm that this PR fixes issue https://github.com/hyperledger/besu/issues/3786

**Review by ahamlat — APPROVED** [review]
Nice work

**Comment by dhallatmaine** [comment]
> I was able to reproduce without this PR the OOM error, by starting Besu with -Xmx3g and running trace_replayBlockTransactions on block 16627443 on mainnet.
> 
> ```
> {"@timestamp":"2023-02-14T15:44:15,731","level":"INFO","thread":"vert.x-worker-thread-0","class":"AbstractEngineNewPayload","message":"Imported #16,627,962 / 186 tx / base fee 31.94 gwei / 16,956,329 (56.5%) gas / (0x065c993d09265a30a4639607532271925f015622823aafd31f99cd3d8de70c59) in 3.739s. Peers: 25","throwable":""}
> {"@timestamp":"2023-02-14T15:44:26,837","level":"INFO","thread":"vert.x-worker-thread-0","class":"AbstractEngineNewPayload","message":"Imported #16,627,963 / 136 tx / base fee 32.46 gwei / 16,440,973 (54.8%) gas / (0x26433d35d0d0bc21a64d09171d6c1279d393c3ccc4a9f6e4c775d9b620e11921) in 1.128s. Peers: 25","throwable":""}
> {"@timestamp":"2023-02-14T15:44:49,872","level":"WARN","thread":"vertx-blocked-thread-checker","class":"BlockedThreadChecker","message":"Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2541 ms, time limit is 2000 ms","throwable":""}
> {"@timestamp":"2023-02-14T15:45:13,258","level":"ERROR","thread":"nioEventLoopGroup-3-10","class":"DeFramer","message":"Exception while processing incoming message","throwable":" java.lang.OutOfMemoryError: Java heap space\n"}
> {"@timestamp":"2023-02-14T15:45:15,405","level":"WARN","thread":"vert.x-acceptor-thread-0","class":"DefaultChannelPipeline","message":"An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.","throwable":" java.lang.OutOfMemoryError: Java heap space\n\tat io.netty.channel.epoll.EpollServerSocketChannel.newChildChannel(EpollServerSocketChannel.java:102)\n\tat io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:120)\n\tat io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:375)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\n"}
> {"@timestamp":"2023-02-14T15:45:18,171","level":"WARN","thread":"vertx-blocked-thread-checker","class":"BlockedThreadChecker","message":"Thread Thread[vert.x-worker-thread-17,5,main] has been blocked for 65281 ms, time limit is 60000 ms","throwable":" io.vertx.core.VertxException: Thread blocked\n\tat app//org.apache.tuweni.bytes.MutableBytes32.create(MutableBytes32.java:28)\n\tat app//org.apache.tuweni.bytes.Bytes32.leftPad(Bytes32.java:187)\n\tat app//org.hyperledger.besu.ethereum.vm.DebugOperationTracer.captureStack(DebugOperationTracer.java:229)\n\tat app//org.hyperledger.besu.ethereum.vm.DebugOperationTracer.tracePostExecution(DebugOperationTracer.java:73)\n\tat app//org.hyperledger.besu.evm.EVM.runToHalt(EVM.java:330)\n\tat app//org.hyperledger.besu.evm.processor.AbstractMessageProcessor.codeExecute(AbstractMessageProcessor.java:174)\n\tat app//org.hyperledger.besu.evm.processor.AbstractMessageProcessor.process(AbstractMessageProcessor.java:192)\n\tat app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.process(MainnetTransactionProcessor.java:495)\n\tat app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:405)\n\tat app//org.hyperledger.besu.ethereum.mainnet.MainnetTransactionProcessor.processTransaction(MainnetTransactionProcessor.java:204)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.lambda$prepareReplayAction$0(BlockTracer.java:60)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer$$Lambda$2216/0x00000008013a9d60.performAction(Unknown Source)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$0(BlockReplay.java:60)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay$$Lambda$2222/0x00000008013aac98.apply(Unknown Source)\n\tat java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\n\tat java.base@17.0.5/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)\n\tat java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)\n\tat java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)\n\tat java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)\n\tat java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\n\tat java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.lambda$block$1(BlockReplay.java:66)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay$$Lambda$2217/0x00000008013aa188.perform(Unknown Source)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.performActionWithBlock(BlockReplay.java:163)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockReplay.block(BlockReplay.java:52)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.processor.BlockTracer.trace(BlockTracer.java:45)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.traceBlock(TraceReplayBlockTransactions.java:118)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.lambda$resultByBlockNumber$0(TraceReplayBlockTransactions.java:102)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions$$Lambda$2215/0x00000008013a9248.apply(Unknown Source)\n\tat java.base@17.0.5/java.util.Optional.map(Optional.java:260)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.TraceReplayBlockTransactions.resultByBlockNumber(TraceReplayBlockTransactions.java:102)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.findResultByParamType(AbstractBlockParameterMethod.java:88)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.internal.methods.AbstractBlockParameterMethod.response(AbstractBlockParameterMethod.java:102)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.BaseJsonRpcProcessor.process(BaseJsonRpcProcessor.java:42)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TracedJsonRpcProcessor.process(TracedJsonRpcProcessor.java:41)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.TimedJsonRpcProcessor.process(TimedJsonRpcProcessor.java:45)\n\tat app//org.hyperledger.besu.ethereum.api.jsonrpc.execution.JsonRpcExecutor.execute(JsonRpcExecutor.java:92)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.executeRequest(JsonRpcExecutorHandler.java:118)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.executeJsonObjectRequest(JsonRpcExecutorHandler.java:131)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler.lambda$handler$0(JsonRpcExecutorHandler.java:78)\n\tat app//org.hyperledger.besu.ethereum.api.handlers.JsonRpcExecutorHandler$$Lambda$1222/0x00000008011c2280.handle(Unknown Source)\n\tat app//io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)\n\tat app//io.vertx.ext.web.impl.BlockingHandlerDecorator$$Lambda$1548/0x00000008012a8ac0.handle(Unknown Source)\n\tat app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)\n\tat app//io.vertx.core.impl.ContextImpl$$Lambda$1442/0x0000000801244438.handle(Unknown Source)\n\tat app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)\n\tat app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)\n\tat app//io.vertx.core.impl.ContextImpl$$Lambda$1438/0x0000000801243980.run(Unknown Source)\n\tat java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base@17.0.5/java.lang.Thread.run(Thread.java:833)\n"}
> ```
> 
> By installing this PR and running the same test (starting Besu with -Xmx3g and running trace_replayBlockTransactions on block 16627443 on mainnet), I haven't had the error with several tests. I can confirm that this PR fixes issue #3786

A bit of an update from our side. We have cut a new docker image and pushed this out as our reader node that our BlockScout connects to. As of this point, we are seeing some side effects that we are trying to address:
```
2023-02-13T19:08:32.284 application=indexer fetcher=block_catchup first_block_number=5938582 last_block_number=5938573 [error] ** (FunctionClauseError) no function clause matching in EthereumJSONRPC.quantity_to_integer/1
    (ethereum_jsonrpc 5.0.0) lib/ethereum_jsonrpc.ex:398: EthereumJSONRPC.quantity_to_integer(nil)
    (ethereum_jsonrpc 5.0.0) lib/ethereum_jsonrpc/http.ex:147: EthereumJSONRPC.HTTP.standardize_response/1
    (elixir 1.13.1) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ethereum_jsonrpc 5.0.0) lib/ethereum_jsonrpc/http.ex:44: EthereumJSONRPC.HTTP.chunked_json_rpc/3
    (ethereum_jsonrpc 5.0.0) lib/ethereum_jsonrpc/request_coordinator.ex:86: anonymous fn/3 in EthereumJSONRPC.RequestCoordinator.perform/4
    (ethereum_jsonrpc 5.0.0) lib/ethereum_jsonrpc/request_coordinator.ex:106: EthereumJSONRPC.RequestCoordinator.trace_request/2
    (ethereum_jsonrpc 5.0.0) lib/ethereum_jsonrpc.ex:493: EthereumJSONRPC.fetch_blocks_by_params/3
    (stdlib 3.17) timer.erl:166: :timer.tc/1
```

We are not sure whether this is related to this change or something from 22.10.3 -> main. Our next steps are going to be to backport this change to the 22.10.X branch, cut a new docker image, and try that as our reader node. I will update with our findings.

**Comment by ahamlat** [comment]
Could you share the logs from Besu side @dhallatmaine ?

**Comment by ahamlat** [comment]
I will check from side if the result is the same with and without this PR

**Comment by ahamlat** [comment]
@Gabriel-Trintinalia @macfarla The result is different with and without this PR, could you check ?
```
ls -lh
total 576K
-rw-rw-r--  1 ahamlat ahamlat 144K Feb 14 17:57 rpcCallResult.txt
-rw-rw-r--  1 ahamlat ahamlat 428K Feb 14 18:32 rpcCallResultWithoutPR.txt
```

**Comment by dhallatmaine** [comment]
> @Gabriel-Trintinalia @macfarla The result is different with and without this PR, could you check ?
> 
> ```
> ls -lh
> total 576K
> -rw-rw-r--  1 ahamlat ahamlat 144K Feb 14 17:57 rpcCallResult.txt
> -rw-rw-r--  1 ahamlat ahamlat 428K Feb 14 18:32 rpcCallResultWithoutPR.txt
> ```

We are still investigating. I unfortunately lost those logs for now. We have tried running latest Besu(without this PR) with BlockScout and this error no longer happens. We are in process of backporting to 22.10.x, but with your findings and running latest, it is starting to make me believe this fix isn't 100%.

**Comment by dhallatmaine** [comment]
We have backported this change to 22.10.x and are running it now in our dev and qa. It seems to be working as expected, no OOM and no other issues so far.

Running this change from main does seem to cause the elixir issue in BlockScout mentioned above.

**Comment by macfarla** [comment]
@dhallatmaine what's the reason you're backporting to 22.10.x - are you just waiting for a stable 23.1.0 ? (coming soon!) 

With the elixir issue from BlockScout - is that a blocker? 
This `no function clause matching in EthereumJSONRPC.quantity_to_integer/1` makes me think it's to do with changing types somewhere, I'm guessing another change in main, not this PR

**Comment by dhallatmaine** [comment]
@macfarla our nodes in production (and in our other environments) are currently using 22.10.x. We attempted to connect a reader node running the latest (with my PR) to these nodes, but ran into these issues.

We were unable to reindex our BlockScout due to the issue mentioned above, so it was a blocker for us. Running this PR on 22.10.x in our environments seems to be working fine so far.

**Comment by ahamlat** [comment]
@dhallatmaine Could you test this workaround from blockscout team while looking into this from our side ?

> EXPORT INDEXER_RECEIPTS_BATCH_SIZE=100

ref. https://github.com/blockscout/blockscout/issues/6747

**Review by ahamlat — CHANGES_REQUESTED** [review]
The output result of trace_replayBlockTransactions is not correct as mentioned above. Checking the output result against main and 22.10.3 for the same blocks, we have different outputs from this PR. The output from 22.10.3 and main (commit 97edc67c3058b0a82f2f1bc69dbc87f93b2557cc) is the same, but different from the output of this PR

**Comment by ahamlat** [comment]
@dhallatmaine You can generate those files just by redirecting the output to a file :

- Install version x of Besu and launch curl -X POST --data '{"jsonrpc": "2.0", "method": "trace_replayBlockTransactions","params": ["0xFDD1A6",["trace"]],"id": 1}' http://127.0.0.1:8545 > rpcCallResultWithoutPR.txt

- Install this PR and launch curl -X POST --data '{"jsonrpc": "2.0", "method": "trace_replayBlockTransactions","params": ["0xFDD1A6",["trace"]],"id": 1}' http://127.0.0.1:8545 > rpcCallResult.txt

Compare these two files.
I spend some time analyzing the PR today, and I found that it is not working currently. It seems that the transactions are not executed. When I added toList().stream() here https://github.com/hyperledger/besu/pull/5062/files#:~:text=transactionProcessor))%3B, it worked but it is similar to the previous implementation (with List), as this generates an Out Of Memory error

**Comment by Gabriel-Trintinalia** [comment]
Closing in favour of https://github.com/hyperledger/besu/pull/5131

**Pull request closed without merging**
