### PR TITLE
Fix unhandled exception

### PR DESCRIPTION
**Pull request by pinges**
## PR description

Fixes an unhandled exception: 

{"@timestamp":"2024-10-08T01:07:36,808","level":"ERROR","thread":"vert.x-eventloop-thread-3","class":"ContextImpl","message":"Unhandled exception","throwable":" java.util.NoSuchElementException\n\tat 1.next(CircularFifoQueue.java:385)\n\tat java.base/java.util.AbstractCollection.contains(AbstractCollection.java:112)\n\tat org.hyperledger.besu.ethereum.p2p.discovery.internal.PeerTable.isIpAddressInvalid(PeerTable.java:217)\n\tat 

Fixes https://github.com/hyperledger/besu/issues/7733

### CODE REVIEW

**Review by macfarla — COMMENTED** [review]
can you add a test to show the problem that is fixed

**Comment by pinges** [comment]
> can you add a test to show the problem that is fixed

That is really hard, as the problem was a race condition.
In the code we were iterating over the collection, checking hasNext(), then getNext(). In the Implementation of getNext() in the collection the first thing that is done is checking hasNext(), which failed and threw the NoSuchElementException.

**Review by siladu — APPROVED** [review]
LGTM

**Review by jframe — APPROVED** [review]

**Comment by macfarla** [comment]
> > can you add a test to show the problem that is fixed
> 
> That is really hard, as the problem was a race condition. In the code we were iterating over the collection, checking hasNext(), then getNext(). In the Implementation of getNext() in the collection the first thing that is done is checking hasNext(), which failed and threw the NoSuchElementException.

ok fair enough

**Review by macfarla — APPROVED** [review]

**Pull request merged**
