### PR TITLE
Add group heading to command options

### LINKED ISSUE #2757: Add headings to Besu help
This can be done with PicoCLI headings https://picocli.info/quick-guide.html#_section_headings

See related ticket about formatting of the help output
https://github.com/hyperledger/besu/issues/541

### Description
As a developer, I want help grouped sensibly so that it's easy to find what I'm looking for.

Suggested groupings:
GraphQL
JSON-RPC HTTP 
JSON-RPC WebSockets
Metrics
Miner
Privacy
Permissions
Tx pool
(everything else can remain ungrouped)

### Acceptance Criteria
* Besu help has headings for related CLI options

### Steps to Reproduce (Bug)
1. besu --help

### PR DESCRIPTION
**Pull request by sandrawangyx**
## PR description

This PR continues to group the CLI options together.

- JSON-RPC HTTP
- JSON-RPC WebSockets
- Metrics
- Miner
- Privacy
- Permissions
- Tx pool

## Fixed Issue(s)

fixes #2757 

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by macfarla** [comment]
Engine JSON-RPC Options
 should be a separate heading (and only relevant if --Xmerge-support)

and can we uppercase HTTP 
s/Json RPC Http Options/JSON-RPC HTTP Options/

**Comment by sandrawangyx** [comment]
> Engine JSON-RPC Options should be a separate heading (and only relevant if --Xmerge-support)
> 
> and can we uppercase HTTP s/Json RPC Http Options/JSON-RPC HTTP Options/

@macfarla  thanks for the comment :) 

do you mean all the options with `--engine-xxx` prefix should have their group? 

and am I correct: when this `--Xmerge-support` is one, then we merge the options with --engine prefix with all other JSON-RPC options?

**Comment by macfarla** [comment]
> > Engine JSON-RPC Options should be a separate heading (and only relevant if --Xmerge-support)
> > and can we uppercase HTTP s/Json RPC Http Options/JSON-RPC HTTP Options/
> 
> @macfarla thanks for the comment :)
> 
> do you mean all the options with `--engine-xxx` prefix should have their group?
> 
> and am I correct: when this `--Xmerge-support` is on, then we merge the options that have --engine prefix with all other JSON-RPC options?

yes and yes. 
also - sorry for delayed reply - I've been off sick with covid, just catching up on everything today.

**Comment by sandrawangyx** [comment]
oh hope all is well now @macfarla

**Review by macfarla — APPROVED** [review]
Looking good!

**Comment by macfarla** [comment]
I would like to add headings for 
P2P Discovery
this would be p2p options, the discovery ones and max-peers, and banned-node-ids, and bootnodes. and remote-connections ones

Pruning
API gas price

**Pull request merged**
