### PR TITLE
Use github arm64 runners

### LINKED ISSUE #7026: Migrate from self-hosted hyp-ci-linux-arm64 to besu-arm64 runner
For arm docker builds we currently target the self-hosted `hyp-ci-linux-arm64` but now there is a github provided runner enabled

### PR DESCRIPTION
**Pull request by seanyoung**
Now that the arm64 runners are re-created with the ubuntu 22.04 image, docker and other tools are available.

See #7054, revert #7087 and closed PR #7171

fixes #7026

Unfortunately this can only be tested in the hyperledger/besu repo and not on forks

### CODE REVIEW

**Comment by seanyoung** [comment]
Cc: @ryjones

**Review by siladu — APPROVED** [review]
LGTM

**Comment by siladu** [comment]
@seanyoung it worked this time 🎉 
https://github.com/hyperledger/besu/actions/runs/9382845736/job/25835177099

**Comment by seanyoung** [comment]
I've also created https://github.com/hyperledger/besu-native/pull/173 for the native arm64 job

**Pull request merged**
