### PR TITLE
[23.4] Remove GoQuorum privacy

### LINKED ISSUE #4886: Remove GoQuorum-compatible privacy feature (23.4)
This feature was deprecated in 23.1 
See https://github.com/hyperledger/besu/pull/4879
And can be removed in 23.4 to simplify block and transaction processing.

### PR DESCRIPTION
**Pull request by macfarla**
Remove GoQuorum compatible privacy

Fixes #4886

- [x] next release is 23.4
- [x] acceptanceTestsNonMainnet passed in CI
- [x] Besu with other types of privacy still works as expected

### CODE REVIEW

**Comment by macfarla** [comment]
with this change - if you send a GoQuorum private transaction via EthSigner, it is rejected with "method not enabled" because it sends a `goquorum_storeRaw` to Besu which Besu rejects
-> suggested change to EthSigner https://github.com/ConsenSys/ethsigner/pull/500 - to actively reject this type of transaction

**Review by pinges — COMMENTED** [review]
I've done a "find all" within Besu for goquorum and I found a few error codes in JsonRpcError.java that are related to goquorum privacy:
GOQUORUM_NO_PRIVATE_FOR
GOQUORUM_ONLY_STANDARD_MODE_SUPPORTED
GOQUORUM_LOOKUP_ID_NOT_AVAILABLE
GOQUORUM_V_VALUE

In RpcMethod.java I found
GOQUORUM_ETH_GET_QUORUM_PAYLOAD
GOQUORUM_STORE_RAW

In BlockHeader.java there is a method that returns the private logs bloom:
 getPrivateLogsBloom()

We might be able to get rid of the v parameter for Transaction (org/hyperledger/besu/ethereum/core/Transaction.java)

There is a method on BlockProcessor line 149 that we should be able to get rid of

KeyValueSegmentIdentifier.java contains 
GOQUORUM_PRIVATE_WORLD_STATE
GOQUORUM_PRIVATE_STORAGE

TransactionDecoderTest.java lines 41 and 88

That's all I can find right now :-)

**Comment by macfarla** [comment]
> I've done a "find all" within Besu for goquorum and I found a few error codes in JsonRpcError.java that are related to goquorum privacy: GOQUORUM_NO_PRIVATE_FOR GOQUORUM_ONLY_STANDARD_MODE_SUPPORTED GOQUORUM_LOOKUP_ID_NOT_AVAILABLE GOQUORUM_V_VALUE
> 
> In RpcMethod.java I found GOQUORUM_ETH_GET_QUORUM_PAYLOAD GOQUORUM_STORE_RAW
> 
> In BlockHeader.java there is a method that returns the private logs bloom: getPrivateLogsBloom()
> 
> We might be able to get rid of the v parameter for Transaction (org/hyperledger/besu/ethereum/core/Transaction.java)
> 
> There is a method on BlockProcessor line 149 that we should be able to get rid of
> 
> KeyValueSegmentIdentifier.java contains GOQUORUM_PRIVATE_WORLD_STATE GOQUORUM_PRIVATE_STORAGE
> 
> TransactionDecoderTest.java lines 41 and 88
> 
> That's all I can find right now :-)

Thanks @pinges removed all those things!

**Comment by macfarla** [comment]
> with this change - if you send a GoQuorum private transaction via EthSigner, it is rejected with "method not enabled" because it sends a `goquorum_storeRaw` to Besu which Besu rejects -> suggested change to EthSigner [ConsenSys/ethsigner#500](https://github.com/ConsenSys/ethsigner/pull/500) - to actively reject this type of transaction

Leaving EthSigner as is. User will get "method not enabled" if they try to send a GoQuorum private tx via EthSigner to Besu.

**Review by shemnon — APPROVED** [review]
I really like how this removes `GoQuorumOptions`

**Comment by lucassaldanha** [comment]
End of an era!

**Comment by non-fungible-nelson** [comment]
Reminder to merge for tomorrow @macfarla

**Pull request merged**
