### PR TITLE
Deprecate --Xp2p-peer-lower-bound

### LINKED ISSUE #6376: delete -Xp2p-peer-lower-bound
delete this flag

### PR DESCRIPTION
**Pull request by macfarla**
Deprecate CLI option --Xp2p-peer-lower-bound and remove usage

Fixes #6376

### CODE REVIEW

**Comment by macfarla** [comment]
although it's early access, this option is mentioned in the docs so that needs to be updated eg https://besu.hyperledger.org/public-networks/how-to/connect/manage-peers#limit-peers

**Review by pinges — APPROVED** [review]
LGTM

**Comment by arnili** [comment]
I'm using this option per the documentation at https://besu.hyperledger.org/public-networks/how-to/connect/manage-peers#limit-peers to balance my incoming/outgoing connections to 50:50 after significantly reducing my number of peers.

If this option is removed most/all my connections will be outgoing and I will be a net-burden to the network.

**Comment by macfarla** [comment]
Hi @arnili - I recommend you look at https://besu.hyperledger.org/public-networks/how-to/connect/manage-peers#limit-remote-connections and also static nodes configuration might be a good option for you if you want to maintain connections to specific nodes. Additionally, whether connections are initiated inbound or outbound makes no difference, once the nodes are connected as peers they are treated equally. If you have questions still - reach out in discord!

**Pull request merged**
