### PR TITLE
Add Gary Schulte as Maintainer

### PR DESCRIPTION
**Pull request by RatanRSur**
Gary has provided [significant commits](https://github.com/hyperledger/besu/commits?author=garyschulte) that have improved the quality of Besu.

Voting ends 2 weeks from the publication of this PR.

For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.

### CODE REVIEW

**Review by NicolasMassart — APPROVED** [review]
@garyschulte you have my vote.

**Review by shemnon — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
+1

**Review by macfarla — APPROVED** [review]

**Review by ajsutton — APPROVED** [review]

**Review by pinges — APPROVED** [review]

**Review by lucassaldanha — APPROVED** [review]

**Review by matkt — APPROVED** [review]
+1

**Review by alexandratran — APPROVED** [review]

**Review by abdelhamidbakhta — APPROVED** [review]
Looks good to me.

**Review by MadelineMurray — APPROVED** [review]

**Review by bgravenorst — APPROVED** [review]
LGTM

**Comment by garyschulte** [comment]
🥳   Merge me 🙏

**Review by usmansaleem — APPROVED** [review]
+1

**Comment by matkt** [comment]
The majority approved so I merge and @garyschulte becomes Maintainer

**Pull request merged**
