### PR TITLE
Add Sajida Zouarhi to maintainers

### PR DESCRIPTION
**Pull request by atoulme**
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>
Sajida has started helping manage Github issues and collaborating with the existing maintainers to help coordinate the development of Besu.

Voting ends 2 weeks from the publication of this PR.

For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.

## Approval of this PR

- [ ] 2 weeks voting period (ends June 3rd 2021)
- [x] at least 3 approvals
- [x] no veto
- [x] absolute majority makes it pass immediately (currently 11 approvals).

### CODE REVIEW

**Review by MadelineMurray — APPROVED** [review]

**Review by garyschulte — APPROVED** [review]
🚢

**Review by NicolasMassart — APPROVED** [review]
Approved and I added this PR that may be interesting to review in parallel https://github.com/hyperledger/besu/pull/2307

**Review by RatanRSur — APPROVED** [review]

**Comment by shemnon** [comment]
From a process perspective #2307 needs to pass first, as without it there is insufficient justification in this PR.  Hence I vote block until either #2307 or a similar proposal passes. (to be explicit, if #2307 passes my block is removed).

**Comment by NicolasMassart** [comment]
> From a process perspective #2307 needs to pass first, as without it there is insufficient justification in this PR. Hence I vote block until either #2307 or a similar proposal passes. (to be explicit, if #2307 passes my block is removed).

As @shemnon I think we can deal with the PRs #2303 #2304 and #2307 in parallel in order to reduce the duration but only merge #2303 and #2304 if #2307 is merged first.

#2303 and #230 need a bit more detail and justifications to me. I know Sajida and Vijay are doing a great work. I work with them. However it's not about convincing colleagues but all other Besu maintainers and make sure we don't bypass rules that we created.

**Review by macfarla — APPROVED** [review]

**Review by pinges — APPROVED** [review]

**Review by ajsutton — APPROVED** [review]

**Review by usmansaleem — APPROVED** [review]
LGTM

**Review by jframe — APPROVED** [review]

**Comment by NicolasMassart** [comment]
Assuming @atoulme  is voting in favor, we reached 11 which is the absolute majority.

**Pull request merged**
