### PR TITLE
BESU-110: Fixing broken links on the CHANGELOG 

### PR DESCRIPTION
**Pull request by SweeXordious**
## PR description
This PR fixes the broken links on the CHANGELOG.
This is the second PR in this sense since the first one had some rebase problems i couldn't solve.
## Fixed Issue(s)

Fixes BESU-110

### CODE REVIEW

**Comment by SweeXordious** [comment]
The problem from the last pull request i have made is still here.

The problem is with the DCO bot that asks me to run: 

`git rebase HEAD~16 --signoff`

But when i do, i get this:

`error: unknown option "signoff"`

after cloning the repo on my local machine.

Thank you.

**Comment by CjHare** [comment]
To get the `--signoff` working, you'll need to set some git config on your development machine:

Set your legal name in the git configuration: 
`git config user.name "Legal Name"` 

Set your email in the git configuration: 
`git config user.email "email@address"`

Source: https://wiki.hyperledger.org/display/BESU/How+to+Contribute#HowtoContribute-HowtoworkwithDCO

**Comment by SweeXordious** [comment]
> To get the `--signoff` working, you'll need to set some git config on your development machine:
> 
> Set your legal name in the git configuration:
> `git config user.name "Legal Name"`
> 
> Set your email in the git configuration:
> `git config user.email "email@address"`
> 
> Source: https://wiki.hyperledger.org/display/BESU/How+to+Contribute#HowtoContribute-HowtoworkwithDCO

Right now when i run the `git rebase HEAD~17 --signoff` i get some patches error. And when i execute `git am --show-current-patch` i get the following output:
```
commit 8951dd6cdbf207547d04000b498cdabec6b81715
Author: Jason Frame <jasonwframe@gmail.com>
Date:   Mon Nov 18 09:18:46 2019 +1000

    Allow use a external JWT public key in authenticated APIs (#183)
    
    Signed-off-by: Jason Frame <jasonwframe@gmail.com>

diff --git a/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/net/ExpectNetVersionPermissionJsonRpcUnauthorizedResponse.java b/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/login/ExpectLoginDisabled.java
similarity index 62%
rename from acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/net/ExpectNetVersionPermissionJsonRpcUnauthorizedResponse.java
rename to acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/login/ExpectLoginDisabled.java
index 91e5ecfd6..6f68a38c1 100644
--- a/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/net/ExpectNetVersionPermissionJsonRpcUnauthorizedResponse.java
+++ b/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/login/ExpectLoginDisabled.java
@@ -12,23 +12,16 @@
  *
  * SPDX-License-Identifier: Apache-2.0
  */
-package org.hyperledger.besu.tests.acceptance.dsl.condition.net;
+package org.hyperledger.besu.tests.acceptance.dsl.condition.login;
 
 import org.hyperledger.besu.tests.acceptance.dsl.condition.Condition;
 import org.hyperledger.besu.tests.acceptance.dsl.node.Node;

```

So i think it is as @NicolasMassart pointed. I should rename my master, pull the fresh one from upstream then push it to my fork...

**Comment by SweeXordious** [comment]
I just did the following:
rename my master, pull a fresh master from upstream then push my work

> git fetch upstream
> git checkout master
> git merge upstream/master


But I am still facing the same errors as before:

> Right now when i run the `git rebase HEAD~17 --signoff` i get some patches error. And when i execute `git am --show-current-patch` i get the following output:
> 
> ```
> commit 8951dd6cdbf207547d04000b498cdabec6b81715
> Author: Jason Frame <jasonwframe@gmail.com>
> Date:   Mon Nov 18 09:18:46 2019 +1000
> 
>     Allow use a external JWT public key in authenticated APIs (#183)
>     
>     Signed-off-by: Jason Frame <jasonwframe@gmail.com>
> 
> diff --git a/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/net/ExpectNetVersionPermissionJsonRpcUnauthorizedResponse.java b/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/login/ExpectLoginDisabled.java
> similarity index 62%
> rename from acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/net/ExpectNetVersionPermissionJsonRpcUnauthorizedResponse.java
> rename to acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/login/ExpectLoginDisabled.java
> index 91e5ecfd6..6f68a38c1 100644
> --- a/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/net/ExpectNetVersionPermissionJsonRpcUnauthorizedResponse.java
> +++ b/acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/login/ExpectLoginDisabled.java
> @@ -12,23 +12,16 @@
>   *
>   * SPDX-License-Identifier: Apache-2.0
>   */
> -package org.hyperledger.besu.tests.acceptance.dsl.condition.net;
> +package org.hyperledger.besu.tests.acceptance.dsl.condition.login;
>  
>  import org.hyperledger.besu.tests.acceptance.dsl.condition.Condition;
>  import org.hyperledger.besu.tests.acceptance.dsl.node.Node;
> ```
>

**Comment by SweeXordious** [comment]
Finally i managed to fix all the issues.
What i did:
- Cleaned the fork and restarted from upstream
````
git remote add upstream /url/to/original/repo
git fetch upstream
git checkout master
git reset --hard upstream/master  
git push origin master --force 
````

- Made my changes then pushed to master. Thus the changes get added to the PR automatically.

**Comment by NicolasMassart** [comment]
Hi, nice work! However, given the number of links, I used a linckecker tool to check all the links and it looks like there's some remaining dead links in this page:
I honestly don't know what to do with all these deprecated issues links, any idea is welcome. I would say pointing the issues links to the Besu Jira root but I'm not sure, @MadelineMurray any idea?

> FILE: CHANGELOG.md
> [✖] https://github.com/PegaSysEng/pantheon/pull/
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Deploying-Besu/High-Availability/
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Getting-Started/Run-Docker-Image/
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Permissions/Permissioning-Overview/
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Permissions/Onchain-Permissioning/Production/
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Tutorials/Create-Permissioned-Network/
> [✖] https://github.com/PegaSysEng/pantheon/blob/master/DOC-STYLE-GUIDE.md
> [✖] https://github.com/PegaSysEng/pantheon/blob/master/docs/development/running-developer-builds.md
> [✖] https://github.com/PegaSysEng/pantheon/issues/956
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Reference/Besu-CLI-Syntax/#public-key
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Consensus-Protocols/IBFT/
> [✖] https://github.com/PegaSysEng/pantheon/issues/662
> [✖] https://github.com/PegaSysEng/pantheon/issues/854
> [✖] https://github.com/PegaSysEng/pantheon/issues/839
> [✖] https://github.com/PegaSysEng/pantheon/issues/821
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Reference/Besu-CLI-Syntax/
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Getting-Started/Run-Docker-Image/#data-directory
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Getting-Started/Run-Docker-Image/#custom-configuration-file
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Getting-Started/Run-Docker-Image/#custom-genesis-file
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Configuring-Besu/Node-Keys/#specifying-a-custom-node-private-key-file
> [✖] https://docs.pantheon.pegasys.tech/en/latest/Configuring-Besu/Using-Configuration-File/
> [✖] https://github.com/PegaSysEng/pantheon/issues/248
> [✖] https://github.com/PegaSysEng/pantheon/issues/228
> [✖] https://github.com/PegaSysEng/pantheon/issues/215
> [✖] https://github.com/PegaSysEng/pantheon/issues/251
> [✖] https://github.com/PegaSysEng/pantheon/issues/186
> [✖] https://github.com/PegaSysEng/pantheon/issues/245
> [✖] https://github.com/PegaSysEng/pantheon/issues/206
> [✖] https://github.com/PegaSysEng/pantheon/issues/233
> [✖] https://github.com/PegaSysEng/pantheon/issues/184
> [✖] https://github.com/PegaSysEng/pantheon/issues/189
> [✖] https://github.com/PegaSysEng/pantheon/issues/191

**Comment by SweeXordious** [comment]
Hello,
@NicolasMassart  That or we can just add a **deprecated** or something like that next to them to point that they no longer exist..

**Comment by CjHare** [comment]
> FILE: CHANGELOG.md
As the changelog is a summary of the work on the project, the broken links provide no context 

Either link to the new issue (if it was moved) or replace with a line summarising the purpose of the commit(s).

Whether summarising the commits should be done in this PR or another, is an open question (but I'd lean towards a new PR for that).

**Comment by SweeXordious** [comment]
> Either link to the new issue (if it was moved) or replace with a line summarising the purpose of the commit(s).
> 
> Whether summarising the commits should be done in this PR or another, is an open question (but I'd lean towards a new PR for that).

So what should i add to this PR ?

**Comment by CjHare** [comment]
> So what should i add to this PR ?
@MadelineMurray any thoughts?

**Comment by MadelineMurray** [comment]
I think the best way forward is to: 
- Delete the broken links to Jira issues.  I don't think it's worth the effort to go back and fix these.  The change is in the PR anyway. 
- Change the broken doc links to point to the doc home page - https://besu.hyperledger.org/en/stable/ 

Thanks for contributing and working through the DCO issues.

**Comment by SweeXordious** [comment]
> I think the best way forward is to:
> 
>     * Delete the broken links to Jira issues.  I don't think it's worth the effort to go back and fix these.  The change is in the PR anyway.
> 
>     * Change the broken doc links to point to the doc home page - https://besu.hyperledger.org/en/stable/
> 
> 
> Thanks for contributing and working through the DCO issues.

Will do, Thank you

**Comment by SweeXordious** [comment]
I fixed the broken links as pointed by @NicolasMassart via the changes suggested by @MadelineMurray. 
Now after i use the [Link Checker](https://github.com/tcort/markdown-link-check) i find only this broken link:
```
ERROR: 1 dead links found!

[✖] https://github.com/PegaSysEng/pantheon/pull/ → Status: 404
```
What should i do to it ? any thoughts ?

**Comment by SweeXordious** [comment]
Fixed last link by linking to the issue it refers to. 
Now, this PR is ready to be reviewed, i think.

**Pull request merged**
