### PR TITLE
remove removeAllKeysUnless from interfaces and its implemntation

### PR DESCRIPTION
**Pull request by yehia67**
fix issue #861

### CODE REVIEW

**Comment by RatanRSur** [comment]
If you click on the failing unit tests, you'll see that we have a check to ensure that public-facing apis aren't broken by commits. It's fine in this case because it's a public facing commit so you'll need to grab the updated hash in the failing unit test log and replace that in the `build.gradle` for the plugin api. Otherwise it looks good!

**Comment by RatanRSur** [comment]
@yehia67 Let me know if you have any confusion about what to do next

**Comment by yehia67** [comment]
@RatanRSur I am trying to figure out how to the hash is calculated on the` build.gradel`  file.

**Comment by yehia67** [comment]
I check this line
`checkPluginAPIChanges.dependsOn(':plugin-api:checkAPIChanges')
`
but I am not sure yet as I am not familiar with gradel.

**Comment by yehia67** [comment]
found it found it sorry. I checked the wrong `build.gradel` file I will commit it now

**Comment by RatanRSur** [comment]
Cool, just for reference, this is the message:
```
Execution failed for task ':plugin-api:checkAPIChanges'.
> For the Plugin APIs the checksum of the project did not match what was expected.
  
  If this is a deliberate change where you have thought through backwards compatibility,
  then update "Expected" for "Calculated" in the appropriate build.gradle as the knownHash for this task.
  Expected   : x6hLH75JBKLM8mNFz7n0ALRw4TWiDONJuum53da4jTY=
  Calculated : d2HD6T1USSbVL9OftLuNlmJO25d1WscqrxCIimdhtgM=

```

**Comment by yehia67** [comment]
@RatanRSur  yes I replaced this hash but I don't understand this error
`c2cc993041352da0db37935cd939cda333d4ec26 is missing Signed-off-by line.
`
Do I need to update branch?

**Comment by RatanRSur** [comment]
If you go to the details on the DCO action failure, you'll see the steps to take. Your most recent commit wasn't DCO signed I suppose.

**Comment by yehia67** [comment]
yes I use this command to fix the problem 
`git push --force-with-lease origin 861-Remove-unneeded-removeAllKeysUnless-method-from-key-value-storage-interfaces`

**Comment by RatanRSur** [comment]
@yehia67 There's another contributors commit in the PR, would you mind removing that and force pushing?

**Comment by yehia67** [comment]
No, I don't mind at all.

**Comment by yehia67** [comment]
Could you please give me detailed instructions as I am new at open-source contribution and I am afraid I will cause a bug.

**Comment by RatanRSur** [comment]
Sure thing!

I can always give you the fish eventually but I'll try teaching you to fish first so you can carry this knowledge onto your future contributions. You'll want to use `git rebase`. Here is a guide about it

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

You want to use `rebase` to get rid of the commit you don't recognize and that post should show how you might do that.

**Comment by yehia67** [comment]
Thank you! I should remove the last commit I had done then force push right?

**Comment by RatanRSur** [comment]
Not the last commit you did but the commit named: `Expose price bump to a CLI flag. (#930) `

**Comment by RatanRSur** [comment]
Actually, I just remembered that this is going to be squashed into one commit so I don't think it matters.

**Comment by yehia67** [comment]
Okay, thank you @RatanRSur  I really appreciate your help.

**Comment by RatanRSur** [comment]
Feel free to peruse the other good first issues and see if there's anything else you want to help with.

**Pull request merged**
