### PR TITLE
Upgrade rocksdb jni lib from 8.3.2 to 9.7.3

### PR DESCRIPTION
**Pull request by ahamlat**
## PR description
Upgrade rocksdb jni lib from 8.3.2 to 9.7.3

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by fab-10 — APPROVED** [review]

**Comment by macfarla** [comment]
where's this one at in terms of testing @ahamlat ?

**Comment by ahamlat** [comment]
@macfarla still testing, I'm OOO so let's keep it open until I share the results

**Comment by macfarla** [comment]
> @macfarla still testing, I'm OOO so let's keep it open until I share the results

I'm changing to DRAFT as we're waiting for test results

**Comment by ahamlat** [comment]
I see no difference in terms of block processing performance between both versions.

image

But version 9.7.3 seems to use more memory compared to 8.3.2

image

Which is related to off heap allocations

image

I'm also checking this old comment` // 8.9.1 causes a bug with a FOREST canary` on forest nodes

**Comment by ahamlat** [comment]
Running the nodes for more almost 2 weeks showed similar memory usage between the two versions of RocksDB. Off-heap memory is also very close.

image

**Pull request merged**
