### PR TITLE
[Issue 6301] Refactor BadBlockManager

### PR DESCRIPTION
**Pull request by mbaxter**
## PR description
Refactor `BadBlockManager` handling - move it out of `ProtocolSpec` and into `ProtocolContext`.  This will make it simpler to expose bad block events through the plugins API.  

This refactor simplifies access to `BadBlockManager` and improves the clarity of the codebase. Accessing `BadBlockManager` through `ProtocolSpec` is misleading because it implies this object is changing depending on the current spec / milestone.  However, this is not the case - `BadBlockManager` is a global cache unrelated to the spec. 

Now, instead of accessing the `BadBlockManager` in a roundabout way by pulling the latest spec:
```
Blockchain chain = protocolContext.getBlockchain();
BlockHeader head = chain.getChainHeader()
BadBlockManager badBlockManager = protocolSchedule
        .getByBlockHeader(head)
        .getBadBlocksManager()
``` 
You can just grab it directly from `ProtocolContext.getBadBlockManager()`. 

**Notes for the reviewer**:
The first commit moves the instantiation of `BadBlockManager` from `ProtocolScheduleBuilder` to `BesuControllerBuilder`.  This introduces a lot of changes because `BadBlockManager` now has to be injected into `ProtocolScheduleBuilder`.  The second commit pushes `BadBlockManager` into `ProtocolContext`, which also introduces a lot of changes - mostly in tests.  The rest of the commits are much smaller and more manageable. 

## Fixed Issue(s)
Part of #6301

### CODE REVIEW

**Comment by siladu** [comment]
Just wanted to note the following issue comment since removing BadBlockManager from ProtocolSpec was previously considered and decided against.

https://github.com/hyperledger/besu/issues/5153#issuecomment-1548878777

The most relevant point is:

> It make sense to partition bad blocks by fork since they blocks may be valid/invalid depending on different fork rules.

@daniellehrner may have some further thoughts about this.

At the time of #5153, the plugin use cases mentioned for this PR were not previously considered so that may changes things.

**Comment by mbaxter** [comment]
> It make sense to partition bad blocks by fork since they blocks may be valid/invalid depending on different fork rules.

Isn't a block necessarily on a single deterministic fork?  When would a block move between forks?

**Comment by siladu** [comment]
> Isn't a block necessarily on a single deterministic fork? When would a block move between forks?

Agree a block wouldn't move between forks. 
Trying to remember the context of that comment...`debug_getBadBlocks` isn't fork-aware, so for example it's potentially misleading to send a request after the Cancun timestamp has passed and get a response containing bad blocks that are no longer invalid according to Cancun spec. 
But think you're right...it's possible for the API user to filter based on blockNumber themselves so it's just a semantic change to the API, not a big deal.

**Review by siladu — APPROVED** [review]
LGTM. Thanks for the review-friendly commits and description 👍

**Pull request merged**
