### PR TITLE
[LOGGING] snap pipeline errors and peer reputation

### PR DESCRIPTION
**Pull request by gfukushima**
## PR description
* Log any possible throwables we're getting up on snap requests
* also changes from #6831 - log peer as part of peer reputation registerX()

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by macfarla — DISMISSED** [review]

**Comment by macfarla** [comment]
maybe we want to throttle this, depending on how spammy it is?

**Comment by macfarla** [comment]
combined this with changes from #6831

**Comment by macfarla** [comment]
> going to test this on some nodes and see how spammy it is

too spammy at info level. changed to debug.

**Review by garyschulte — APPROVED** [review]
🚢

**Pull request merged**
