### PR TITLE
Revise Memory Expansion

### PR DESCRIPTION
**Pull request by shemnon**
## PR description

Move from a perfect fit memory expansion model to an exponential expansion model.

Signed-off-by: Danno Ferrin <danno.ferrin@gmail.com>

## Documentation

- [X] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [X] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by garyschulte — APPROVED** [review]
Locally seeing 24 -> 5.4  :+1:

:ship:

**Review by jflo — APPROVED** [review]

**Comment by shemnon** [comment]
@garyschulte count your decimal places.

**Comment by garyschulte** [comment]
`time` included in jvm startup presumably.  😉

**Comment by holiman** [comment]
Shouldn't you have changed this too? 
```
  @Override
  public String toString() {
    return Bytes.wrap(memBytes).toHexString();
  }
```
-- so that it returns only the `activeMemory` area, not the unued-but-allocated data at the end? 
I don't know if this is used anywhere, but if it's e.g. used in the json output for tracing, then it needs to be fixed.

**Pull request merged**
