### PR TITLE
Support free gas networks when using London fee market

### PR DESCRIPTION
**Pull request by siladu**
In order to support [free gas private networks](https://besu.hyperledger.org/en/stable/HowTo/Configure/FreeGas/) in a London/EIP1559 context, I propose that we support setting a zero baseFee.

If `baseFeePerGas` is overridden as 0 wei, then bypass the need for a transaction to have a gas price of >= 7 wei.

The genesis would look something like this:
```
{
  "config": {
    ...
    "londonBlock": 0,
    ...
  },
  "baseFeePerGas": "0x0",
  "nonce": "0x0",
  ...
}
```

One potential downside is that once baseFeePerGas is set to 0, there's no going back for that chain. You can still use `--min-gas-price` to enforce _some_ gas, but the London base fee calculation will be forever opted out of as a consequence of the zero baseFee in the genesis block. This also means no ether would get burned since base fee will always be zero.

This is currently blocking users with free gas networks from upgrading past the Berlin fork.

## Fixed Issue(s)

Fixes https://github.com/hyperledger/besu/issues/3374
Fixes https://github.com/hyperledger/besu/issues/3763

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by antonydenyer** [comment]
It's a fiddly one! We talked about previously over at https://github.com/hyperledger/besu/pull/3397 

Should we tie the minimum to what is set in the genesis?

**Comment by siladu** [comment]
> It's a fiddly one! We talked about previously over at https://github.com/hyperledger/besu/pull/3397

It is indeed! I saw that PR, was planning on asking for your review for this ;) 

Pre-London, configuring a free gas network only involved setting --min-gas-price=0 on the nodes but this fix would involve the user setting baseFee to zero as well, which is a bit annoying but documentable.
 
The reason I've gone with that for now is because zero baseFee is also required to pass this validation: https://github.com/hyperledger/besu/blob/645fdd08ee940cb770d2415a7a958b32d0c3b94c/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java#L134-L141

Another option could be to default baseFee to zero and set it explicitly for public networks.

Was trying to get my head around how the fee gets burned and if there would be any implications for this configuration.

**Review by shemnon — APPROVED** [review]

**Comment by siladu** [comment]
Keeping open for @garyschulte to look at.

**Review by garyschulte — APPROVED** [review]
0 or >=7 seems like a viable way to support both zero gas and "working" base fee networks :+1:

**Pull request merged**
