### PR TITLE
Error out on permissions config accounts-allowlist validation errors. [#7138]

### PR DESCRIPTION
**Pull request by krsh24**
## PR description
When allow_accountlist in "permissions_config.toml" have duplicate or incorrect Ethereum addresses the functionality is to throw IllegalStateException during start-up. Currently, the validation errors are ignored and not logged to the log file as well.
This change will ensure the config file is valid before starting up the node.

## Fixed Issue(s)

https://github.com/hyperledger/besu/issues/7138

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] unit tests: `./gradlew build`
- [x] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by macfarla — APPROVED** [review]
thanks for your contribution!

**Comment by macfarla** [comment]
appreciate you adding tests for the broken bit. they just don't quite compile

/home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java:122: error: cannot find symbol
> Task :config:test
    assertThrows(
    ^
  symbol:   method assertThrows(Class<IllegalStateException>,()->{ cont[...]m); })
  location: class AccountLocalConfigPermissioningControllerTest
/home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java:136: error: cannot find symbol
    assertThrows(
    ^
  symbol:   method assertThrows(Class<IllegalStateException>,()->{ cont[...]m); })
  location: class AccountLocalConfigPermissioningControllerTest

> Task :ethereum:permissioning:compileTestJava
Note: /home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeLocalConfigPermissioningControllerTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

**Comment by krsh24** [comment]
> appreciate you adding tests for the broken bit. they just don't quite compile
> 
> /home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java:122: error: cannot find symbol
> 
> > Task :config:test
> > assertThrows(
> > ^
> > symbol:   method assertThrows(Class,()->{ cont[...]m); })
> > location: class AccountLocalConfigPermissioningControllerTest
> > /home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java:136: error: cannot find symbol
> > assertThrows(
> > ^
> > symbol:   method assertThrows(Class,()->{ cont[...]m); })
> > location: class AccountLocalConfigPermissioningControllerTest
> 
> > Task :ethereum:permissioning:compileTestJava
> > Note: /home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeLocalConfigPermissioningControllerTest.java uses or overrides a deprecated API.
> > Note: Recompile with -Xlint:deprecation for details.
> > 2 errors

Embarrassing! Just pushed a commit @macfarla

**Comment by macfarla** [comment]
> > appreciate you adding tests for the broken bit. they just don't quite compile
> > /home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java:122: error: cannot find symbol
> > > Task :config:test
> > > assertThrows(
> > > ^
> > > symbol:   method assertThrows(Class,()->{ cont[...]m); })
> > > location: class AccountLocalConfigPermissioningControllerTest
> > > /home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/AccountLocalConfigPermissioningControllerTest.java:136: error: cannot find symbol
> > > assertThrows(
> > > ^
> > > symbol:   method assertThrows(Class,()->{ cont[...]m); })
> > > location: class AccountLocalConfigPermissioningControllerTest
> > 
> > 
> > > Task :ethereum:permissioning:compileTestJava
> > > Note: /home/runner/work/besu/besu/ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/NodeLocalConfigPermissioningControllerTest.java uses or overrides a deprecated API.
> > > Note: Recompile with -Xlint:deprecation for details.
> > > 2 errors
> 
> Embarrassing! Just pushed a commit @macfarla

no probs! except now DCO is broken - you should be able to follow the instructions https://github.com/hyperledger/besu/pull/7161/checks?check_run_id=25717305093 to fix it. It's just a matter of adding a signoff to your most recent commit. :)

**Pull request merged**
