### PR TITLE
split ATs into privacy/permissioning/etc and the rest

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>

Ref #4921 
* split ATs into two groups - mainnet and non-mainnet
* run "non-mainnet" ATs on nightly build
* did 2 runs with run both groups of ATs on PRs (to make sure it works - the right numbers of tests are run - see comments for details)

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by macfarla** [comment]
https://app.circleci.com/pipelines/github/hyperledger/besu/19947/workflows/dd3cf62e-ce43-42d8-948f-a857a3edd16e
* "essential" ATs took 5.5 minutes - 116 tests
* "privacy/permissioning/clique/bft" 23min - 91 tests (this is longer than normal ATs - maybe bc we were running 2 x XL executors? but if we move it to nightly, we don't mind if it takes a bit longer than normal.)

**Comment by macfarla** [comment]
earlier build - ATs 395 tests https://app.circleci.com/pipelines/github/hyperledger/besu/19946/workflows/baed83c0-6ed1-41f1-a8d4-be04779ca780/jobs/122093

**Comment by macfarla** [comment]
second run with both groups of ATs - https://app.circleci.com/pipelines/github/hyperledger/besu/19948/workflows/06eb58a8-c8b4-4559-b17a-3189b6d73005

**Comment by macfarla** [comment]
run with just mainnet ATs on PR build https://app.circleci.com/pipelines/github/hyperledger/besu/19949/workflows/edf382f3-2e01-460a-a8c9-5b870429778a

**Review by usmansaleem — APPROVED** [review]
LGTM

**Pull request merged**
