### PR TITLE
Added command line option --static-nodes-file (#1414)

### PR DESCRIPTION
**Pull request by terrencecooke**
Now able to inject static nodes by explicitly specifying
a static nodes JSON file (.json) on the command line

Signed-off-by: Terrence Cooke <terrence.s.cooke@gmail.com>

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by RatanRSur** [comment]
Thanks for the contribution! We need to add a test in BesuCommandTest that makes sure `StaticNodesParser.fromPath(staticNodesPath, getEnodeDnsConfiguration());` gets called with the correct values when the option is absent and present with a value. You should be able to copy and edit a test from that class that does something similar.

**Comment by terrencecooke** [comment]
Sure, I'll get on it.

**Comment by RatanRSur** [comment]
Also, before I forget, this is going to need a line in the changelog as well.

**Comment by terrencecooke** [comment]
I added three test methods to class BesuCommandTest. One tests a valid file is used, a second test when an ill-formed JSON file is specified, and a third tests when the option is used but no parameter is specified.

I attempted to test when an file that does not exist is given as a parameter:
 --static-nodes-file=some-file-that-does-not-exist

But no message was returned at all during the test build.  This is contrary to running besu manually, you'll get the message:

 | main | INFO  | StaticNodesParser | StaticNodes file /home/tcooke/code/gitprojs/besu/build/install/besu/staticdir/some-file-that-does-not-exist does not exist, no static connections will be created.

Any suggestions on how I should proceed?
I was considering omitting this particularly test. What do you think?

**Comment by terrencecooke** [comment]
As far as adding a line to the changelog, what should be added: the tests and the added cli option, or just the tests?

**Comment by terrencecooke** [comment]
I've decided that the best test for when a file does not exist is to make sure no error message was returned. The commantOutput will be ignored for now.

As for the changelog, I'll simply add the line from the commit message:
Added command line option --static-nodes-file (#1414)

**Comment by terrencecooke** [comment]
Added tests to BesuCommand and a line to CHANGELOG.md

**Review by RatanRSur — APPROVED** [review]

**Comment by how2applyIT** [comment]
Running besu as a background service fails with "unable to parse static nodes file.  Using a config.toml to start.  Loads fine from TCL and does not require a static nodes jason.  I don't have a jason to parse.  Why is besu failing?  

brad@tiny:~/besu-21.1.3$ sudo journalctl -fu besu.service
-- Logs begin at Mon 2021-03-29 13:07:26 EDT. --
Mar 30 09:45:03 tiny besu[67434]: ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.82021-03-30 09:45:03.522-04:00 | main | INFO  | AbstractAltBnPrecompiledContract | Using LibEthPairings native alt bn128
Mar 30 09:45:04 tiny besu[67434]: 2021-03-30 09:45:04.173-04:00 | main | INFO  | SECP256K1 | Using native secp256k1
Mar 30 09:45:04 tiny besu[67434]: 2021-03-30 09:45:04.178-04:00 | main | INFO  | Besu | Starting Besu version: besu/v21.1.3/linux-x86_64/openjdk-java-11
Mar 30 09:45:04 tiny besu[67434]: 2021-03-30 09:45:04.342-04:00 | main | INFO  | Besu | Static Nodes file = /media/brad/Ether/mainnet/static-nodes.json
Mar 30 09:45:04 tiny besu[67434]: 2021-03-30 09:45:04.343-04:00 | main | INFO  | StaticNodesParser | Unable to parse static nodes file (/media/brad/Ether/mainnet/static-nodes.json)
Mar 30 09:45:04 tiny besu[67434]: /media/brad/Ether/mainnet/static-nodes.json
Mar 30 09:45:04 tiny besu[67434]: To display full help:
Mar 30 09:45:04 tiny besu[67434]: besu [COMMAND] --help
Mar 30 09:45:04 tiny systemd[1]: besu.service: Main process exited, code=exited, status=1/FAILURE
Mar 30 09:45:04 tiny systemd[1]: besu.service: Failed with result 'exit-code'.
Mar 30 09:45:09 tiny systemd[1]: besu.service: Scheduled restart job, restart counter is at 214.

**Comment by RatanRSur** [comment]
Does the file `/media/brad/Ether/mainnet/static-nodes.json` exist? If so, what are its contents?

**Comment by how2applyIT** [comment]
I don't have one.  I can start besu using a config.toml from command line with no problem.  but when I start besu as a background service, using the same config.toml file,  it fails wanting a static file.  what am I doing wrong?

**Comment by how2applyIT** [comment]
here is config.toml
miner-enabled=false
graphql-http-enabled=false
sync-mode="FAST"
rpc-http-host="127.0.0.1"
pruning-enabled=false
rpc-ws-enabled=false
data-path="/media/brad/Ether/goerli"
rpc-http-enabled=true
rpc-http-apis=["ETH", "NET", "WEB3"]
network="goerli"
rpc-http-port="8545"

**Comment by how2applyIT** [comment]
running service with a new user and group named: besu

**Comment by RatanRSur** [comment]
and the besu.service file as well please :)

**Comment by how2applyIT** [comment]
sure! 
[Unit]
Description=Ethereum besu client
After=network.target
Wants=network.target
[Service]
User=besu
Group=besu
Type=simple
Restart=always
RestartSec=5
ExecStart=/home/brad/besu-21.1.3/bin/besu --config-file=/home/brad/besu-21.1.3/>
[Install]
WantedBy=default.target

**Comment by RatanRSur** [comment]
It's odd because clearly your service is using `/media/brad/Ether/mainnet` as its data path but your `config.toml` specifies `data-path="/media/brad/Ether/goerli"`. What's going on at the end of this line `ExecStart=/home/brad/besu-21.1.3/bin/besu --config-file=/home/brad/besu-21.1.3/>` ? That `>` is suspicious

**Pull request merged**
