### PR TITLE
BESU-146 - return better gas estimate service error message if possible

### PR DESCRIPTION
**Pull request by anthonybuckle**
Signed-off-by: Anthony Buckle <anthonybuckle@gmail.com>

## PR description

Here is a suggestion to improve gas estimate service error messages concerning jira ticket BESU-146.

## Fixed Issue(s)
Fixes: https://jira.hyperledger.org/browse/BESU-146

### CODE REVIEW

**Comment by CjHare** [comment]
It would be good to see an addition test in `EthEstimateGasTest` that covers the flow you've changed i.e an error is encountered by the function returned by `gasEstimateResponse()`.

**Comment by anthonybuckle** [comment]
Hi CjHare, Thanks for the feedback and no problem. Are you referring to the case where gasEstimateResponse(requestContext) fails and returns a null value. That would lead line 68 orElse(errorResponse(requestContext, JsonRpcError.INTERNAL_ERROR)) returning an error response. It would need a test case. Do you know any good ways to make gasEstimateResponse(requestContext) fail in the test cases using when().thenReturn(). Those methods are private in the class.

**Comment by CjHare** [comment]
Ah, actually I was thinking a test for the flow that goes through line 93 (the replacement of `null` for `errorResponse(request, result.getValidationResult());`, where the result is unsuccessful and the validation result would be something other than `INTERNAL_ERROR`.

The case you raise is a also good one, let me ponder over it 🤔

**Comment by CjHare** [comment]
@anthonybuckle,  I suspect the case you mention (the `orElse()` on line 68) may already be covered by `shouldReturnErrorWhenTransientTransactionProcessorReturnsEmpty()`

**Comment by CjHare** [comment]
```

**Comment by CjHare** [comment]
This test would cover the additional flow incorporating the simulation validation result 🙂 

```
  @Test
  public void shouldReturnErrorWhenTransactionProcessorReturnsUnsuccessfulSimulation() {
    final JsonRpcRequestContext request = ethEstimateGasRequest(callParameter());
    setupUnsuccessfulSimulation(UPFRONT_COST_EXCEEDS_BALANCE);

    final JsonRpcResponse expectedResponse =
        new JsonRpcErrorResponse(null, JsonRpcError.TRANSACTION_UPFRONT_COST_EXCEEDS_BALANCE);

    Assertions.assertThat(method.response(request))
        .isEqualToComparingFieldByField(expectedResponse);
  }

  private void setupUnsuccessfulSimulation(final TransactionValidator.TransactionInvalidReason reason){
    final  TransactionSimulatorResult simulation = mock(TransactionSimulatorResult.class);
    when(simulation.isSuccessful()).thenReturn(false);
    when(simulation.getValidationResult()).thenReturn( ValidationResult.invalid(reason));
    when(transactionSimulator.process(eq(modifiedCallParameter()), eq(1L)))
        .thenReturn(Optional.of( simulation ));
  }
```

**Comment by anthonybuckle** [comment]
Hi @CjHare, I confirmed that test case shouldReturnErrorWhenTransientTransactionProcessorReturnsEmpty does handle the orElse() case. I also added the exceeds balance test case as you suggested. Thanks for your help. Cheers.

**Comment by timbeiko** [comment]
@anthonybuckle if you'd like this change included in the release notes, please add a line about it to the [changelog](https://github.com/hyperledger/besu/blob/master/CHANGELOG.md#141). Thanks!

**Comment by anthonybuckle** [comment]
> @anthonybuckle if you'd like this change included in the release notes, please add a line about it to the [changelog](https://github.com/hyperledger/besu/blob/master/CHANGELOG.md#141). Thanks!

@timbeiko Sure no problem. A PR for the updated changelog is here: https://github.com/hyperledger/besu/pull/451

**Pull request merged**
