### PR TITLE
Added a JSON-RPC method to set target block gas limit (Issue #544)

### LINKED ISSUE #544: Add JSON-RPC method to set target block gas limit
As a user, I want to be able to change the block gas limit while Besu is running. Using the `--target-gas-limit` option requires starting and stopping Besu.

Acceptance criteria: Add a JSON-RPC API methods (`admin_changeTargetGasLimit`) to update the target gas limit.

### PR DESCRIPTION
**Pull request by terrencecooke**
## Description

Added a JSON-RPC method to set target block gas limit

## Fixed Issue(s)

fixes #544

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by RatanRSur** [comment]
Hey! Thanks for the PR. Would you mind taking a look at #1409? I'm proposing some changes that would set me up to add some commits to this PR that I think would clean some things up.

**Comment by RatanRSur** [comment]
@terrencecooke , did you get a chance to see the discussion around that PR?

**Comment by terrencecooke** [comment]
Sorry for the delay in my reply. 
I did review the discussion in #1409.  I agree, having GasLimitCalculator is easier to follow than Function<Long, Long>.  I didn't notice any change to the mutation in #1402, so I assume that will be left in tact.
Looking forward to seeing my contribution being used by the world.

**Comment by RatanRSur** [comment]
Cool! Do you mind if I go ahead and add commits to this PR to fix things up?

**Comment by terrencecooke** [comment]
Sure, add this commit to mine. Now is as good a time to make those enhancements as any.
Looking forward to seeing the end result.

**Comment by RatanRSur** [comment]
Did you click `Allow edits from maintainers`?

**Comment by terrencecooke** [comment]
Yes, "Allow edits by maintainers" is enabled

**Comment by terrencecooke** [comment]
Yes, "Allow edits by maintainers" is enabled

**Review by shemnon — APPROVED** [review]

**Pull request merged**
