### PR TITLE
adds Matthew Whitehead as a maintainer

### PR DESCRIPTION
**Pull request by jflo**
I propose to add  @matthew1001 as a Besu project maintainer.

@matthew1001 contributed with many high quality commits:

- has implemented new JSON-RPC api endpoints, per execution api specs
- has improved error reporting in apis
- has improved configurability for non PoS networks

Here are [their past contributions on Besu project](https://github.com/hyperledger/besu/pulls?q=is:pr+author:matthew1001+is:closed).

Voting ends two weeks from today.

For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.

### CODE REVIEW

**Review by macfarla — APPROVED** [review]
thanks for your contributions @matthew1001 !

**Review by siladu — APPROVED** [review]
🎉 

(nbd, but I think the new entry maybe should go under macfarla?)

**Review by jframe — APPROVED** [review]

**Comment by macfarla** [comment]
> 🎉
> 
> (nbd, but I think the new entry maybe should go underneath macfarla?)

good catch - that's why we need 12 approvals on these PRs... and actually now that I have my fine-toothed comb out - alphabetically - should be below matkt

**Review by gfukushima — APPROVED** [review]

**Review by Gabriel-Trintinalia — APPROVED** [review]

**Review by daniellehrner — APPROVED** [review]

**Review by garyschulte — APPROVED** [review]
🚢

**Review by pinges — APPROVED** [review]

**Review by usmansaleem — APPROVED** [review]
👍🏼

**Review by fab-10 — APPROVED** [review]

**Review by lucassaldanha — APPROVED** [review]

**Review by matkt — APPROVED** [review]

**Review by ahamlat — APPROVED** [review]

**Pull request merged**
