### PR TITLE
Add Network Upgrades & Anvil Default Accounts to Dev Genesis

### PR DESCRIPTION
**Pull request by RatanRSur**
Signed-off-by: Ratan (Rai) Sur <ratan.r.sur@gmail.com>

## PR description
My EIP-1559 tx got rejected by the dev network so I added all the new upgrades :)

The next part is more of a feature. I added the default accounts for `anvil` to streamline the local node -> besu pipeline. This way it can be a drop in replacement.

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by shemnon** [comment]
My google-fu is weak.  Can you provide a pointer to anvil?

Also, can you (as part of the comment element) explain where these keys come from so we aren't creating more "revealed" key material?  Such as "Anvil demo user number 1"

I think we made the "new key" mistake for the first three accounts.

**Comment by RatanRSur** [comment]
You're not alone haha. No one can google for anvil sucessfully. https://github.com/foundry-rs/foundry/tree/master/anvil

Sure, I'll update the comments.

**Comment by shemnon** [comment]
I love that the check word for the mnemonic phrase is 'junk'

**Comment by shemnon** [comment]
I would approve, but there is a unit test broken by adding the istanbulBlock field. I'm not picky about how it's resolved.

**Comment by iamhsk** [comment]
This PR should be merged after fixing the broken tests. Updating the dev genesis file story can be found here: #4125

**Comment by macfarla** [comment]
@RatanRSur I'm assuming you've done what you need with this one and moved on. We've created an issue to break the dependency between the privacy tests and the dev genesis file. It's in our backlog but we're working on other priorities for now.

**Comment by macfarla** [comment]
closing this PR. Needs further work to decouple tests from the dev.json as per #4125

**Pull request closed without merging**
