### PR TITLE
Support Version Rollbacks for RocksDB

### PR DESCRIPTION
**Pull request by RatanRSur**
## PR description
Primary:

This fixes an issue where rolling back the default database version could cause an error. It's important that the loading logic depends only on the database version so we can have full control. It's still fine to set auxiliary properties like isSegmentIsolationSupported as we go through the creation process.

Other:

Extend the plugin interface with Closeable

### CODE REVIEW

**Comment by RatanRSur** [comment]
Hey @ryjones, I believe @shemnon reached out and addressed this?

**Comment by ryjones** [comment]
> Hey @ryjones, I believe @shemnon reached out and addressed this?

correct - I'm wrong, ignore me

**Comment by RatanRSur** [comment]
No worries! I believe that once you mark your comment as resolved, the change requested block will be lifted

**Comment by RatanRSur** [comment]
One more thing - can you withdraw your approval? We use those for signaling that someone has done a complete code review and thinks the changes are ready to be merged.

**Comment by ryjones** [comment]
> One more thing - can you withdraw your approval? We use those for signaling that someone has done a complete code review and thinks the changes are ready to be merged.

Tell me what to click and where. I can't find an option for me to dismiss my own review

**Comment by RatanRSur** [comment]
I had to look it up myself! Turns out I can do it myself but so that you know.

Where it says 1 approval, the drop down will have your name. On the right side overflow menu there's a `Dismiss Review` button

**Pull request merged**
