### PR TITLE
Update to Log4j 2.17.0

### PR DESCRIPTION
**Pull request by fredriksvantes**
## Changelog
Apache Log4j2 versions 2.0-alpha1 through 2.16.0 did not protect from uncontrolled recursion from self-referential lookups. When the logging configuration uses a non-default Pattern Layout with a Context Lookup (for example, $${ctx:loginId}), attackers with control over Thread Context Map (MDC) input data can craft malicious input data that contains a recursive lookup, resulting in a StackOverflowError that will terminate the process. This is also known as a DOS (Denial of Service) attack.

- [X] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by fredriksvantes** [comment]
Already being handled in https://github.com/ConsenSys/teku/commit/a0d19d2c5c4c7d6119154f44dfff6d7aed5fb246

**Comment by fredriksvantes** [comment]
Already being handled in https://github.com/hyperledger/besu/commit/e734059f109de1776a00478246836074054f918d

**Comment by shemnon** [comment]
[This](https://github.com/hyperledger/besu/commit/e734059f109de1776a00478246836074054f918d) wan't merged to main.  Feel free to commit this.

**Review by shemnon — APPROVED** [review]

**Comment by shemnon** [comment]
**however** the dco issue must be resolved.

**Comment by macfarla** [comment]
Thanks for this @fredriksvantes - you'll need to do a merge on the changelog as well as the DCO :/

**Review by macfarla — APPROVED** [review]

**Review by shemnon — APPROVED** [review]

**Pull request merged**
