### PR TITLE
chore: Removed Privacy ATs

### LINKED ISSUE #7347: Remove Privacy ATs - have been disabled for some time
Remove privacy AT classes and associated testing resources - look for AT classes that extend this base class -
java/org/hyperledger/besu/tests/acceptance/dsl/privacy/PrivacyAcceptanceTestBase.java

### PR DESCRIPTION
**Pull request by pr9t**
## Fixed Issue(s)
Closes #7347 

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [x] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Comment by macfarla** [comment]
@pr9t you'll need to add signoff to your commits to satisfy DCO - follow the instructions here https://github.com/hyperledger/besu/pull/7530/checks?check_run_id=29343327854

**Comment by macfarla** [comment]
(alternatively, you can close this PR and redo your changes with signoff, sometimes frankly that is easier!)

**Comment by macfarla** [comment]
the change itself looks fine :)

**Comment by pr9t** [comment]
@macfarla I have signoff my commit in the same PR.

**Comment by macfarla** [comment]
@pr9t 
can you run this locally - 
`./gradlew compileTestJava`
there are a few more classes that extended ParameterizedEnclaveTestBase that need removing as well eg PrivGetPrivateTransactionAcceptanceTest

**Comment by pr9t** [comment]
@macfarla I have removed the classes that extend PrivateLogFilterAcceptanceTest and FlexiblePrivacyAcceptanceTestBase. The results are as follows:

- unit tests were successful
- acceptance tests failed
- The command ./gradlew compileTestJava was successful.

**Review by macfarla — APPROVED** [review]
LGTM - thanks for your contribution @pr9t 🚀

**Pull request merged**
