### PR TITLE
add plugins summary

### PR DESCRIPTION
**Pull request by macfarla**
log a summary of plugins at registration time

### CODE REVIEW

**Comment by macfarla** [comment]
eg if RpcEndPoint throws an ex during registration, 

```
####################################################################################################
#                                                                                                  #
# plugins dir /Users/sallymacfarlane/workspace/b2/build/install/besu/plugins                       #
#                                                                                                  #
# SUCCESS LineaTransactionSelectorPlugin                                                           #
# ERROR RollupRpcEndpointServicePlugin                                                             #
#                                                                                                  #
# TOTAL = 1                                                                                        #
#                                                                                                  #
####################################################################################################
```

**Review by fab-10 — COMMENTED** [review]
Like this, and probably is worth to log it a info as part of the configuration overview

**Review by pinges — COMMENTED** [review]
Looking good

**Review by pinges — APPROVED** [review]
LGTM

**Pull request merged**
