### PR TITLE
CALLF and JUMPF rules validation updates

### PR DESCRIPTION
**Pull request by shemnon**
## PR description

Rule 2 in EIP-6206 requires us to check stack prior to JUMPF
Rule 4 in EIP-4759 is about the return stack, not the operand stack.

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Comment by shemnon** [comment]
test is here - https://github.com/ethereum/execution-spec-tests/pull/902

Fails before this PR, passes after.  It's the middle `rule_overflow` case that is relevant.

**Comment by shemnon** [comment]
Test for commit # 2 is here https://github.com/ethereum/execution-spec-tests/pull/907

**Review by fab-10 — APPROVED** [review]

**Comment by fab-10** [comment]
> @fab-10 Will this be merged?

done

**Comment by shemnon** [comment]
@fab-10 Thank you.

**Pull request merged**
