### PR TITLE
Include custom errorprone checks as external dependency

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR description
Include custom errorprone checks as external dependency. Custom errorprone checks has been refactored to its own repo https://github.com/Consensys/errorprone-checks. 

This change will allow to use custom errorprone checks in other projects as well.

Signed-off-by: Usman Saleem <usman@usmans.info>

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by shemnon — CHANGES_REQUESTED** [review]
Splitting into a separate repo and repository is fine, but why are the errorprone checks going to a ConsenSys repository instead of a Hyperleger repository?  @ryjones  can we get a new repo for these so @usmansaleem can move them there?  Probably `besu-errorproone-checks` but i'm flexible on the name.

**Comment by usmansaleem** [comment]
converting to "Draft" for moving to hyperledger specific repo and fixing unit test cases.

**Review by Conanza00 — APPROVED** [review]

**Comment by ryjones** [comment]
https://github.com/hyperledger/besu-errorprone-checks

**Comment by jflo** [comment]
Is this still active or can it be closed? We would like to clean up old outstanding PRs.

**Comment by usmansaleem** [comment]
Closing as not active and very low in priority.

**Pull request closed without merging**
