### PR TITLE
Disable bonsai-limit-trie-logs-enabled if sync-mode=FULL

### PR DESCRIPTION
**Pull request by siladu**
Since [bonsai-limit-trie-logs-enabled has been defaulted to true](https://github.com/hyperledger/besu/pull/7181), instead of preventing startup, implicitly set `bonsai-limit-trie-logs-enabled=false` and warn...

```
besu --sync-mode=FULL
...
2024-07-22 13:34:52.764+10:00 | main | WARN  | Besu | Cannot enable --bonsai-limit-trie-logs-enabled with --sync-mode FULL and --data-storage-format BONSAI. --bonsai-limit-trie-logs-enabled has been automatically disabled.
```

However, if you explicitly try to set it to true, you get a startup error...

```
besu --sync-mode=FULL --bonsai-limit-trie-logs-enabled=true
...
2024-07-22 14:56:11.189+10:00 | main | ERROR | Besu | Failed to start Besu
picocli.CommandLine$ParameterException: Cannot enable --bonsai-limit-trie-logs-enabled with --sync-mode FULL and --data-storage-format=BONSAI. You must set --bonsai-limit-trie-logs-enabled=false or use a different sync-mode
```

```
BESU_SYNC_MODE=FULL BESU_BONSAI_LIMIT_TRIE_LOGS_ENABLED=TRUE besu
...
2024-07-22 15:32:09.687+10:00 | main | ERROR | Besu | Failed to start Besu
picocli.CommandLine$ParameterException: Cannot enable --bonsai-limit-trie-logs-enabled with --sync-mode=FULL and --data-storage-format=BONSAI. You must set --bonsai-limit-trie-logs-enabled=false or use a different sync-mode
```

This also avoids a scenario where private networks can end up starting with sync-mode=FULL and bonsai-limit-trie-logs-enabled=true.

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [x] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by garyschulte — APPROVED** [review]
LGTM.

One ask though, it would be helpful to see these configs (`--bonsai-limit-trie-logs-enabled`, and `--bonsai-trie-logs-pruning-window-size`) in the startup banner logs since they have a significant impact to linea and fleet mode operations

**Comment by siladu** [comment]
@garyschulte its been in the startup banner from the get go 🙂

**Comment by garyschulte** [comment]
> @garyschulte its been in the startup banner from the get go 🙂

I thought that was the case but I didn't see it when I didn't specify it on the command line

**Comment by siladu** [comment]
@garyschulte ahh it's only present when it's enabled. In this case, FULL sync has auto-disabled it and printed a warning log.

Are you suggesting explicitly stating it's disabled in the banner? I'm not sure there's precedent for that with other disabled features but it does seem reasonable since it's no longer experimental and is enabled by default for bonsai.

**Comment by garyschulte** [comment]
I think it was an expectation issue on my part.  I was thinking of adding it as a static element, but of course it only makes sense for bonsai storage format.

It seems reasonable to just rely on its absence to indicate it is disabled 👍

**Pull request merged**
