### PR TITLE
Update SLOAD_GAS cost to 200 in Aztlan Gas Calculator (#23)

### PR DESCRIPTION
**Pull request by edwardmack**
## PR description
Besu was compliance to the specification, but due to "consensus by the majority" we're dropping the gas price of SLOAD to 200.

### CODE REVIEW

**Comment by GregTheGreek** [comment]
We're putting this on `DO NOT MERGE` for the time being. It looks like the ETC community will be using the SLOAD_GAS cost of 800

**Comment by soc1c** [comment]
Official specification: https://github.com/ethereumclassic/ECIPs/pull/293

**Comment by GregTheGreek** [comment]
Should  [ECIP-1086](https://github.com/ethereumclassic/ECIPs/pull/293#pullrequestreview-360656066) be accepted, we will merge this.

**Comment by GregTheGreek** [comment]
This is good to go.

**Comment by shemnon** [comment]
@GregTheGreek @edwardmack does this need a cherry pick for 1.4.0 this week?

**Pull request merged**
