### PR TITLE
[BESU-107] Update 'export-address' sub-command to remove references to 'public key address'

### PR DESCRIPTION
**Pull request by demmojo**
Signed-off-by: Mohamed Abdulaziz <mo@blok-z.com>

## PR description

References to `public key address` were changed to `account address` in the `export-address` sub-command as the term was confusing. 

I suggest adding an 'Address' or 'Account Address' section in https://besu.hyperledger.org/en/stable/Concepts/Node-Keys/ since it might help some people realize that there is a difference between a public key and an Ethereum address. 

## Fixed Issue(s)
Fixes BESU-107.

### CODE REVIEW

**Comment by CjHare** [comment]
Spotless is causing compilation error.

You can run `./gradlew applySpotless` to run spotless locally, then push the changes and the CI checks should pass & the PR can be merged 🙂

**Comment by demmojo** [comment]
Thanks for letting me know about the Spotless issue! 

I think you meant ./gradlew spotlessApply which I ran and then pushed the changes. Please let me know if there is anything else that I need to do.

**Comment by CjHare** [comment]
> I think you meant ./gradlew spotlessApply
Yes, that was it 😁

**Comment by CjHare** [comment]
There are three test methods in the unit tests `org.hyperledger.besu.cli.PublicKeySubCommandTest`  that check the output that need updating to the new text.

methods:
`callingPublicKeyExportAddressSubCommandHelpMustDisplayUsage`
`callingPublicKeySubCommandHelpMustDisplayUsage`
`callingPublicKeySubCommandWithoutSubSubcommandMustDisplayUsage`

**Comment by demmojo** [comment]
Updated `EXPECTED_PUBLIC_KEY_USAGE` and `EXPECTED_PUBLIC_KEY_EXPORT_USAGE` which will fix issues with the test methods mentioned above.

**Pull request merged**
