### PR TITLE
Use Invalid payload attributes error code 

### LINKED ISSUE #6554: Remaining Hive Cancun Failures
## Description

I'm tagging the last 3 failures here for the hive cancun tests.
(note: on [hivecancun](https://hivecancun.ethdevops.io/suite.html?suiteid=1707445951-a0c29c2634925b0c36a58544287836c5.json&suitename=engine-cancun) all other failures pass locally and are due to something internal to the CI).

Specifically from the `engine-cancun` simulator.
```
ForkchoiceUpdatedV3 To Request Shanghai Payload, Null Beacon Root
ForkchoiceUpdatedV2 To Request Shanghai Payload, Non-Null Beacon Root
ForkchoiceUpdatedV2 To Request Cancun Payload, Non-Null Beacon Root
```
These can all be explained from the execution apis spec update in https://github.com/ethereum/execution-apis/pull/498.
We are essentially sending an fcu with invalid payload attributes and hence expect an error reponse of `INVALID_PAYLOAD_ATTRIBUTES`. Besu is returning `INVALID_PARAMS`. Should be a simple parameter fix.

#### Steps to reproduce

Using the latest version of [hive](https://github.com/ethereum/hive/tree/master) run the following command:
```
./hive --sim ethereum/engine --client besu --client-file configs/cancun.yaml --docker.output --sim.limit engine-cancun/"<test_name>"
```

### PR DESCRIPTION
**Pull request by macfarla**
Return "invalid payload attributes" instead of "invalid params" if the payload attributes are, in fact, invalid

fixes #6554

### CODE REVIEW

**Comment by macfarla** [comment]
@jflo I did not yet get a chance to verify this fixes those hive tests

**Comment by macfarla** [comment]
all the "Invalid Payload" tests are now passing off this branch. Running the full engine-cancun suite locally now to verify no regressions.

**Comment by macfarla** [comment]
ok so this fixes 4 out of the 9 currently failing - so all the "Invalid Payload" ones. Similar fix needed for the 3 failing "ForkchoiceUpdatedVX" ones at the top of this screenshot
Screenshot 2024-02-20 at 1 49 46 pm

Ran all the "Invalid Payload" ones locally - 7 tests, 0 failures.

```
NFO[02-19|15:45:56] hiveproxy started                        container=1f873092ddff addr=172.17.0.2:8081
INFO[02-19|15:45:56] API: suite started                       suite=0 name=engine-cancun
INFO[02-19|15:45:56] API: test started                        suite=0 test=1 name="engine-cancun test loader"
INFO[02-19|15:45:56] API: test started                        suite=0 test=2 name="Invalid PayloadAttributes, Zero timestamp, Syncing=False (Cancun) (besu_pr-invalid-payload-atts-git)"
INFO[02-19|15:45:58] API: client besu_pr-invalid-payload-atts-git started suite=0 test=2 container=cad7627f
INFO[02-19|15:46:07] API: test ended                          suite=0 test=2 pass=true
INFO[02-19|15:46:07] API: test started                        suite=0 test=3 name="Invalid PayloadAttributes, Zero timestamp, Syncing=True (Cancun) (besu_pr-invalid-payload-atts-git)"
INFO[02-19|15:46:09] API: client besu_pr-invalid-payload-atts-git started suite=0 test=3 container=2246c4e9
INFO[02-19|15:46:18] API: test ended                          suite=0 test=3 pass=true
INFO[02-19|15:46:18] API: test started                        suite=0 test=4 name="Invalid PayloadAttributes, Parent timestamp, Syncing=False (Cancun) (besu_pr-invalid-payload-atts-git)"
INFO[02-19|15:46:19] API: client besu_pr-invalid-payload-atts-git started suite=0 test=4 container=64af5854
INFO[02-19|15:46:28] API: test ended                          suite=0 test=4 pass=true
INFO[02-19|15:46:28] API: test started                        suite=0 test=5 name="Invalid PayloadAttributes, Parent timestamp, Syncing=True (Cancun) (besu_pr-invalid-payload-atts-git)"
INFO[02-19|15:46:30] API: client besu_pr-invalid-payload-atts-git started suite=0 test=5 container=f97e4d0c
INFO[02-19|15:46:39] API: test ended                          suite=0 test=5 pass=true
INFO[02-19|15:46:39] API: test started                        suite=0 test=6 name="Invalid PayloadAttributes, Missing BeaconRoot, Syncing=False (Cancun) (besu_pr-invalid-payload-atts-git)"
INFO[02-19|15:46:41] API: client besu_pr-invalid-payload-atts-git started suite=0 test=6 container=6de55403
INFO[02-19|15:46:50] API: test ended                          suite=0 test=6 pass=true
INFO[02-19|15:46:50] API: test started                        suite=0 test=7 name="Invalid PayloadAttributes, Missing BeaconRoot, Syncing=True (Cancun) (besu_pr-invalid-payload-atts-git)"
INFO[02-19|15:46:51] API: client besu_pr-invalid-payload-atts-git started suite=0 test=7 container=72ed84a0
INFO[02-19|15:47:00] API: test ended                          suite=0 test=7 pass=true
INFO[02-19|15:47:00] API: test ended                          suite=0 test=1 pass=true
INFO[02-19|15:47:00] API: suite ended                         suite=0
INFO[02-19|15:47:01] simulation ethereum/engine finished      suites=1 tests=7 failed=0
```

**Comment by macfarla** [comment]
ok ready for review for real this time - only 1 remaining hive test failing (was failing before) - "Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun)"

**Review by pinges — APPROVED** [review]
LGTM

**Comment by macfarla** [comment]
> "Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun)"

this test is actually passing when we look online - it just fails locally.

**Pull request merged**
