### PR TITLE
added trace logging of parameter RPC calls

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

LOG.trace of all supplied RPC params

## PR description

Fixes 

## Changelog #3528 

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by garyschulte — COMMENTED** [review]
Can we use `org.hyperledger.besu.util.Slf4jLambdaHelper.traceLambda()` here?  some of these parameters look non-trivial to evaluate

**Comment by macfarla** [comment]
> Can we use `org.hyperledger.besu.util.Slf4jLambdaHelper.traceLambda()` here? some of these parameters look non-trivial to evaluate

I did consider it - but none of them are being evaluated for the log, they are all evaluated earlier and I just log the variable value. Apart from getName() which is trivial to evaluate.

**Comment by macfarla** [comment]
> > Can we use `org.hyperledger.besu.util.Slf4jLambdaHelper.traceLambda()` here? some of these parameters look non-trivial to evaluate
> 
> I did consider it - but none of them are being evaluated for the log, they are all evaluated earlier and I just log the variable value. Apart from getName() which is trivial to evaluate.

added traceLambda where callParams are logged. all other values are already string or long.

**Review by garyschulte — APPROVED** [review]
🚢  ƛ

**Pull request merged**
