### PR TITLE
Execute 'slow' password hash check in worker thread to prevent blocking

### PR DESCRIPTION
**Pull request by magooster**
Execute 'slow' password hash check in worker thread to prevent blocking the event loop.

Signed-off-by: cusden <ian.cusden@gmail.com>

## PR description

Moves the check of the password hash into the worker thread, avoids blocking the main event loop, which could lead to requests failing (timeout).

## Fixed Issue(s)
N/A

### CODE REVIEW

**Comment by rain-on** [comment]
I ran some tests, and couldn't replicate the problem documented.
I.e. it appears the checkPasswordHash is executed within the vertx.executeblocking call - which I had thought executed the work on a worker thread already..
Have I missed something, or is my understanding of how the async handlers not quite right?

**Comment by magooster** [comment]
From https://vertx.io/docs/kdoc/vertx/io.vertx.reactivex.core/-vertx/execute-blocking.html <https://vertx.io/docs/kdoc/vertx/io.vertx.reactivex.core/-vertx/execute-blocking.html>

'When the code is complete the handler resultHandler will be called with the result on the original context (e.g. on the original event loop of the caller).'

So only the readUser method is executed within a vert.x worker thread, the checkPasswordHash method  is executed in the calling vert.x event loop thread

**Comment by rain-on** [comment]
@magooster I read that exact line about 10 minutes after I left my comment.. good fix.

**Comment by rain-on** [comment]
As an alternative - could we install the handlelogin() using a blockinghandler (JsonRpcHttpService:268, then simplify the auth services to be synchronous throughout (removing asyncHandlers etc.)
Or is there a good reason to avoid Vertx's blockingHandler?

**Pull request merged**
