### PR TITLE
trace_get 

### PR DESCRIPTION
**Pull request by mark-terry**
Signed-off-by: Mark Terry <mark.terry@consensys.net>

## PR description
Implementation for trace_get API.
* exclude revertReason from result (matches Besu trace_call and openethereum)

Note this implementation matches openethereum behaviour except for:
* we manually added `creationMethod` to test files even though openethereum 3.2.5 does not include this field (this matches Besu trace_transaction implementation which also includes the `creationMethod` field)

See #2889 

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by macfarla** [comment]
The unit tests failures are explained by: the version of openethereum which generated these test files (3.2.5 installed via homebrew) doesn't have this patch https://github.com/openethereum/openethereum/issues/114

**Comment by matkt** [comment]
regarding the revert reason I think it was added voluntarily even if OE does not manage it. We should ask @shemnon  if he has more context on it.

**Comment by matkt** [comment]
if creationMethod is not needed in this case why we are not using this field ? https://github.com/hyperledger/besu/blob/b0de73fe57bfd8c398939b8e7edef577dd773e04/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTraceGenerator.java#L233

**Comment by macfarla** [comment]
> regarding the revert reason I think it was added voluntarily even if OE does not manage it. We should ask @shemnon if he has more context on it.

for revert reason we have decided to leave as is for now, and made a new ticket #3515 to revisit it.

**Comment by macfarla** [comment]
> if creationMethod is not needed in this case why we are not using this field ?
> 
> https://github.com/hyperledger/besu/blob/b0de73fe57bfd8c398939b8e7edef577dd773e04/ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/tracing/flat/FlatTraceGenerator.java#L233

we decided to include this extra field based on conversation with @mbaxter who is waiting for these APIs to be implemented.

**Review by pinges — APPROVED** [review]
LGTM

**Review by pinges — COMMENTED** [review]
I think we should fix the code smells from Sonar Cloud if they make sense.

**Pull request merged**
