### PR TITLE
Move 3 maintainers to Emeritus status.

### PR DESCRIPTION
**Pull request by shemnon**
I propose moving the following maintainers to Emeritus status, pursuant to the inactivity clause.  Since this is the first such proposal I am extending the window so that _two_ reporting quarters of inactivity be required for movement to Emeritus. (28 Sep 2020 was the start of the Q4 report)

* @iikirilov's last commit was on 24 Mar 2020
* @CjHare's last commit was on 5 Mar 2020
* @rojotek's last commit was on 7 Oct 2019

We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly project. If any of these maintainers express in this PR that the intend to make contributions in the next quarter then they will not be moved to emeritus status.

I propose this vote is open until either an absolute majority of active maintainers (11) votes for the same outcome, or until two weeks has passed (3 April 2021), after which a voting majority will determine the outcome (with a tie resulting in no change).

(edit: @mbaxter was on the original list but (a) has had comments in the past two quarters, which my tooling didn't pick up and (b) has expressed a desire to stay active and contribute. Each reason is independently sufficient.)

### CODE REVIEW

**Comment by shemnon** [comment]
As the author of the PR, this is my obligatory +1 vote.

**Review by atoulme — APPROVED** [review]
As per Hyperledger charter. Thank you for your contributions and hopefully to more soon!

**Review by usmansaleem — APPROVED** [review]
👍 except for @mbaxter.

**Review by lucassaldanha — APPROVED** [review]

**Review by MadelineMurray — APPROVED** [review]

**Review by NicolasMassart — APPROVED** [review]

**Comment by mbaxter** [comment]
I actually have some more recent code review activity, so I'm not sure I fall into this bucket.  In any case, I'd like to stay active and I'll try to step up my contributions.

**Comment by ajsutton** [comment]
I agree we should value code reviews and other forms of participation, not just commits so would be against this change including Meredith.

I'm +1 on moving the other three to emeritus status.

**Comment by shemnon** [comment]
The reporting I have just has commits.  I'll gather a list of code reviews in a few days (tooling...).  Per maintainer policies reviews _do_ count for activity.

Per @mbaxter's statement I will also remove that particular proposal and reduce the list to 3.

**Comment by rojotek** [comment]
As one of the 3 potential contributors moving to an emeritus status, I fully support this 😄

**Comment by timbeiko** [comment]
@shemnon could you add me to this list? I haven't had a significant commit in some time (even including docs). I don't think I should have approve privileges, and am happy to open PRs as needed in the future.

**Comment by shemnon** [comment]
Keeping the Changelog up to date is significant enough.  Since this is a self-nomination I will create a separate PR so there is one PR per cause of action.

**Review by ajsutton — APPROVED** [review]

**Review by macfarla — APPROVED** [review]
LGTM

**Review by RatanRSur — APPROVED** [review]

**Comment by shemnon** [comment]
There were no objections to three of the maintainers being moved to emeritus. One maintainer's change of status had an objection and it was was sustained and will not be moved to emeritus.

**Pull request merged**
