### PR TITLE
Added GraphQL service information to the response results of NetServices.

### LINKED ISSUE #7513: net-service information reading error for GraphQL
Description
Error to read host information about Graphql HTTP using curl "net_services" option.

Steps to Reproduce (Bug)
1. Run the BESU node as follows:

<path>/bin/besu \
  --network=holesky \
  --p2p-port=30303 \
  --rpc-http-port=8545 \
  --rpc-http-enabled=true \
  --rpc-http-cors-origins="*" \
  --engine-rpc-port=8551 \
  --max-peers=25 \
  --rpc-http-enabled=true \
  --sync-mode=SNAP \
  --logging=INFO \
  --data-storage-format=BONSAI \
  --Xbonsai-limit-trie-logs-enabled=true \
  --data-path="/var/lib/besu" \
  --graphql-http-enabled=true \
  --graphql-http-host="0.0.0.0" \
  --graphql-http-port=8549 \
  --engine-jwt-secret=/secrets/jwtsecret

2. Check the port using "netstat -tulnp".
Port for Graphql http to listen on 8549

tcp6       0      0 :::8549                 :::*                    LISTEN      2001774/java                                
tcp6       0      0 :::30303                :::*                    LISTEN      2001774/java                                
tcp6       0      0 127.0.0.1:8545          :::*                    LISTEN      2001774/java                                
tcp6       0      0 127.0.0.1:8551          :::*                    LISTEN      2001774/java 
udp6       0      0 :::30303                :::*                                2001774/java                                
udp6       0      0 :::48848                :::*                                2001774/java  

3. Run Net-Services command.

curl --location 'http://localhost:8545' \
--data '{
    "jsonrpc": "2.0",
    "method": "net_services",
    "params": [],
    "id": 1
}'

Actual behavior: Graphql Host information is not present.
{"jsonrpc":"2.0","id":1,"result":{"jsonrpc":{"host":"127.0.0.1","port":"8545"},"p2p":{"host":"127.0.0.1","port":"30303"}}}

Expected behavior: 
{"jsonrpc":"2.0","id":1,"result":{"jsonrpc":{"host":"127.0.0.1","port":"8545"},"p2p":{"host":"127.0.0.1","port":"30303"}, "graphql":{"host":"127.0.0.1","port":"8549"}}}

Frequency: 100%

Versions (Add all that apply)
Software version: 24.5.1
Java version: openjdk-java-17
OS Name & Version: Ubuntu 22, linux-x86_64

### PR DESCRIPTION
**Pull request by ITStarMan100**
## PR description
Added GraphQL service information to the response results of NetServices.

## Fixed Issue(s)
fixes #7513 

This PR is in response to this [#7513](https://github.com/hyperledger/besu/issues/7513)

[@non-fungible-nelson](https://github.com/macfarla) please review when you have some time.

### CODE REVIEW

**Comment by macfarla** [comment]
@jflo seems like another candidate for daggerization

**Comment by jflo** [comment]
> I can update my code to use Dagger for dependency injection of the GraphQLConfiguration class.
> 
> I would like to ask [@jflo](https://github.com/jflo) if I can proceed by creating a GraphQLConfigurationModule.

Yes! the two most important questions to ask yourself when starting is 1) how is the thing created 2) what class ACTUALLY depends on it, directly. not transitively.

Once you know that, then you need to see if the other things it depends on during 1) can be provided via Dagger. This is often a stumbling block, but more things are added all the time. My [current WIP ](https://github.com/hyperledger/besu/compare/main...jflo:besu:simplifyBesuCommand)is increasing what is available quite a bit.

**Comment by ITStarMan100** [comment]
If the work is still in progress, I can start working on Dagger once it's finished. 
If there are no additional reviews needed for the current code, it might be better to proceed with integration.

**Comment by jflo** [comment]
yes, it's totally appropriate to refactor toward dagger in a future pr.

**Comment by ITStarMan100** [comment]
Will my PR be rejected?

**Comment by jflo** [comment]
> Will my PR be rejected?

No it will not, just waiting on feedback/approval for this and we will merge it.

**Review by jflo — APPROVED** [review]

**Comment by ITStarMan100** [comment]
When I first submitted the PR, the check for testing on my local PC passed.

However, after 5 days and merging with the latest changes from besu main branch, it seems that there is an error in TxPoolOptionsTest.
(txpoolForcePriceBumpToZeroWhenZeroBaseFeeMarket() FAILED
org.mockito.exceptions.verification.WantedButNotInvoked at TxPoolOptionsTest.java:104)

Should I resubmit the PR with the latest changes from besu main branch? 
Or is there a way to fix the issue in TxPoolOptionsTest since @jflo reviewed and approved my PR?

Can @jflo help me to fix this issue?

**Comment by macfarla** [comment]
> When I first submitted the PR, the check for testing on my local PC passed.
> 
> However, after 5 days and merging with the latest changes from besu main branch, it seems that there is an error in TxPoolOptionsTest. (txpoolForcePriceBumpToZeroWhenZeroBaseFeeMarket() FAILED org.mockito.exceptions.verification.WantedButNotInvoked at TxPoolOptionsTest.java:104)
> 
> Should I resubmit the PR with the latest changes from besu main branch? Or is there a way to fix the issue in TxPoolOptionsTest since @jflo reviewed and approved my PR?
> 
> Can @jflo help me to fix this issue?

think that is a flaky test that has been disabled in the meantime. checks now running on your updated PR 🤞

**Pull request merged**
