### PR TITLE
Fix state between transactions is not being maintained for the trace

### PR DESCRIPTION
**Pull request by matkt**
Signed-off-by: Karim TAAM <karim.t2am@gmail.com>

## PR description

Fix state between transactions is not being maintained for the trace.  If the first transaction touches storage the second transaction should be impacted by those changes.

### Test performed 

- Checked this particular test case on Goerli

```json
{
  "method":"debug_standardTraceBlockToFile",
  "params":[
    "0xe72248c356f189254a8bd34ff65c9f0bf12d2ae1ab95d0f41869651b436d845e",
    {
      "disableMemory": true
    }
  ],
  "id":1,
  "jsonrpc":"2.0"
}
```

- Checked that other tracing endpoint are not impacted like `trace_replayBlockTransactions` (1175 blocks)

- Check `debug_standardTraceBadBlockToFile` , `debug_standardTraceBlockToFile` and `debug_getBadBlocks`

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by shemnon** [comment]
Looks good, but there are some tests that will need to be fixed for compile.

How will band blocks be handled?  I see you took out some code that would look in the bad blocks cache.  Is it redundant?

**Comment by matkt** [comment]
> Looks good, but there are some tests that will need to be fixed for compile.
> 
> How will band blocks be handled? I see you took out some code that would look in the bad blocks cache. Is it redundant?

Good catch. While I deleted the modifications related to the `updater` I also deleted the part related to the `badbLock` 🤦‍♂️

To be sure there is no regression. I tested all the APIs with a local Clique Network to make sure everything works (`debug_standardTraceBadBlockToFile` , `debug_standardTraceBlockToFile` and `debug_getBadBlocks`) and I also tried your usecase on Goerli and the tracing API

**Review by shemnon — APPROVED** [review]
Manually testing the call resulted in the correct line of concern, and adding a breakpoint in process transaction resulted in 1 call per transaction, rather than the n^2/2 calls the old method had.

**Review by abdelhamidbakhta — COMMENTED** [review]
Looks good to me.

**Pull request merged**
