### PR TITLE
Moved maintainers to emeritus

### PR DESCRIPTION
**Pull request by macfarla**
## PR description

I propose moving the following maintainers to Emeritus status, pursuant to the inactivity clause. These maintainers have had no activity in besu since June 2023:

@atoulme 
@antonydenyer 
@gezero 
@ajsutton 

We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly project. If any of these maintainers express in this PR that they intend to make contributions in the next quarter, then they will not be moved to emeritus status.

I propose this vote is open until either an absolute majority of active maintainers votes for the same outcome, or until two weeks has passed, after which a voting majority will determine the outcome (with a tie resulting in no change).

### CODE REVIEW

**Comment by ajsutton** [comment]
I think you can add me to the list to make emeritus as well. While I'm still following besu, I haven't had time to contribute to it in quite a while.

**Review by jframe — APPROVED** [review]

**Review by ajsutton — APPROVED** [review]

**Review by siladu — APPROVED** [review]

**Review by antonydenyer — APPROVED** [review]
Still following, but mostly lurking 😃

**Review by antonydenyer — APPROVED** [review]

**Review by daniellehrner — APPROVED** [review]

**Review by fab-10 — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
🐬

**Review by pinges — COMMENTED** [review]
LGTM

**Review by gfukushima — APPROVED** [review]

**Comment by macfarla** [comment]
governance PR https://github.com/hyperledger/governance/pull/331

**Pull request merged**
