### PR TITLE
Add lock to creation of pending transaction stream

### PR DESCRIPTION
**Pull request by matthew1001**
## PR description
This PR does 2 things:

1. Takes a lock on `pendingTransactions` when creating a stream of the transactions
2. Creates a copy of the current transactions when creating the stream, rather than streaming the original list

I have tested the changes with a cut down version `PendingTransactionsForSender` class. There are a couple of points to note for the PR reviewer:

1. I don't know this area of the code well enough to know if there is likely to be a noticeable performance impact of this change. However, without it (or some alternative fix) we'll continue to see `ConcurrentModificationException` be thrown.
2. `List.copyOf` will throw a `ConcurrentModificationException` if the underlying list is changed during the call. Currently `PendingTransactionsForSender.getPendingTransactions(...)` uses that call as well, but without taking a lock on the list. I think this call could fail in the same way and I'm happy to make that change in this PR but would appreciate feedback from the reviewer first.
3. The code path that hit the issue was ultimately down to `AbstractPendingTransactionsSorter.signalInvalidAndRemoveDependentTransactions` being called which wasn't expected for the test I was running. However, the reason for the transaction and its dependent transactions being considered invalid is only logged out if trace is enabled. I wonder if this happens so often that logging it out as a `debug` message instead would be too noisy?

## Fixed Issue(s)
fixes https://github.com/hyperledger/besu/issues/5597

### CODE REVIEW

**Comment by macfarla** [comment]
@fab-10 can you review this one?

**Review by fab-10 — COMMENTED** [review]
Having spent a lot of time on the txpool lately, I reckon that is not easy to fully grasp the concurrency management of this implementation of the txpool at the first view, so I can say that your fix should works because the other paths are covered by the main lock on the `AbstractPendingTransactionsSorter` class, and for the same reason there is an alternative implementation of this fix that should avoid the copy, that I will propose so you can try it.
In any case I do not think that the copy is a big overhead, but instead it is more consistent to managed all the synchronization in the `AbstractPendingTransactionsSorter` that act as the entry point. 
As said in the ticket evaluate switching to the new layered txpool.

**Comment by fab-10** [comment]
@matthew1001 it seems that I cannot open a PR against your fork, so please check the alternative fix here https://github.com/fab-10/besu/commit/2ecc7b95527c79ccbbece596ff52879a818dc98c

**Comment by matthew1001** [comment]
Thanks for the background @fab-10, that's really useful and it's great to know there's a new & improved version of the tx-pool to try. I'd be happy to try it out in our test environment. Regarding the alternative fix, I'll check why you couldn't raise a PR against my fork (probably just an unintentional setting in github) but I can see the point of taking the lock one level higher so the lower level code doesn't need to take a copy of the transactions.

**Comment by matthew1001** [comment]
@fab-10 I've just pushed your suggested change to my branch so the updated PR should be using your alternative fix now

**Review by fab-10 — APPROVED** [review]
LGTM, had you the chance to test this implementation in your network?

**Comment by matthew1001** [comment]
Not yet @fab-10 it will probably be a week or two for us to pull the fix into our own build of Besu and run enough tests to see if we hit it again

**Comment by fab-10** [comment]
if you agree we can merge after the test

**Comment by matthew1001** [comment]
@fab-10 we've had this fix in our test environment for the past week or so and I've not seen any recurrence of the problem. Happy for you to merge it if you're happy that's long enough to flush out any issues.

**Comment by fab-10** [comment]
Thanks for the test, for it is fine to merge it now.

**Pull request merged**
