### PR TITLE
Blobdb for static data

### LINKED ISSUE #4607: Implement and benchmark rocksdb BlobDB for blockchain storage
### Description
As the blockchain storage is append only and block sizes tend to be > 10kb, besu should be able to benefit from RocksDB's [Integrated BlobDB](http://rocksdb.org/blog/2021/05/26/integrated-blob-db.html).  Compaction should be cheaper as the blocks themselves would not be subject tocompaction.

### Acceptance Criteria
* implement blobdb for blockchain storage
* optionally implement blobdb for all values in excess of some fixed size
* benchmark block import via snap-sync with a variety of minimum blob sizes to determine the performance impact
* evaluate the impact of blobdb on overall iops during snap-sync
* evaluate memory consumption for both on and off-heap

### PR DESCRIPTION
**Pull request by fab-10**
## PR description

This PR is built on top of https://github.com/hyperledger/besu/pull/5471, so check it first.
[To only show the diff against #5471](https://github.com/fab-10/besu/compare/variables-storage...fab-10:besu:blobdb-for-static-data) 

This PR introduces optimizations for RocksDB column families that contain static data, i.e. key value entries that are never changed, but only added, like an append log storage, the best example is the blockchain storage, that benefit if [BlobDB ](https://github.com/facebook/rocksdb/wiki/BlobDB) is used for them, since the write amplification is highly reduced, with the result of faster initial sync and less wear out of SSD.

Enabling BlobDB for a column family does not make the db incompatible with a previous version of Besu, however before downgrading Besu you need to run the subcommand `storage revert-variables` to revert changes done in PR #5471 

Preliminary test shows that checkpoint sync is faster with BlobDB enabled, more tests are ongoing, and will share the results later.

## Fixed Issue(s)

fixes #4607

### CODE REVIEW

**Review by jflo — COMMENTED** [review]
So far so good. Have you considered re-using the DataStoreModule from evmtool? We might be able to pull that up into Besu, and use that to provide VariablesStorage to anything that needs it, via BesuComponent.

**Comment by fab-10** [comment]
> So far so good. Have you considered re-using the DataStoreModule from evmtool? We might be able to pull that up into Besu, and use that to provide VariablesStorage to anything that needs it, via BesuComponent.

Not analyzed that part, and given my little knowledge of that part, I will check with you what is necessary for that.

**Comment by garyschulte** [comment]
the diff from 5471 looks good to me.  I am not sure why the failing unit and acceptance tests.

**Comment by fab-10** [comment]
> the diff from 5471 looks good to me. I am not sure why the failing unit and acceptance tests.

unnecessary stubbing, fixed

**Comment by ahamlat** [comment]
Adding some metrics on this PR
### Sync and block block processing timings


**Sync Time**
image

We can also see the difference in block import time, especially from some block number where the node running this PR has a much better block import time.

image

image

**Block processing (post sync)**
Block processing time is very close between both nodes.

image

We can notice also the same performance regarding Forkchoice update (FCU) 

image

### System metrics

Block import time is better because with BlobDB there is [less compaction and thus less write amplification](https://github.com/facebook/rocksdb/wiki/BlobDB).

**Without PR #5475**
image
We can notice below a huge IO activity with a lot of IO waits, 28 ms on average on writes.
image


**With PR #5475**
image
With this PR, there is less IO activity with less IO waits, 9 ms on average on writes.
image

**Review by garyschulte — APPROVED** [review]
🚢

**Pull request merged**
