### PR TITLE
Optimize Dockerfile

### PR DESCRIPTION
**Pull request by c0rv4x**
## PR description

Optimized Dockerfile by combining RUN commands to reduce image layers.

### CODE REVIEW

**Comment by macfarla** [comment]
@cdivitotawela could you review this one

**Comment by cdivitotawela** [comment]
@c0rv4x thanks for the PR. All RUN commands are currently chained together so all in a single image layer. I do not see how the proposed changes reduce any image layers. Anything specific you trying to achieve with the proposed change? 

I will also have another check to see anything I have missed.

**Comment by cdivitotawela** [comment]
@c0rv4x I have checked further and could not see a change in number of image layers nor reduction in image size with the proposed change. I built the image using the existing Dockerfile and proposed Dockerfile. Compared the images checking the history and size. Could not see any benefit with the proposed change.

**Comment by cdivitotawela** [comment]
Proposed change does not reduce number of image layers nor the size of the layer. Closing the PR as its intended purpose is not achieved.

**Pull request closed without merging**
