### PR TITLE
Add Antony Denyer as a maintainer

### PR DESCRIPTION
**Pull request by vmichalik**
Antony has made [significant commits](https://github.com/hyperledger/besu/commits?author=antonydenyer) improving the quality and features of besu, this PR adds him as a maintainer.

Voting ends 2 weeks from the publication of this PR or once a majority of the maintainers [vote](https://github.com/hyperledger/besu/blob/master/MAINTAINERS.md#maintainers-approval-process).

For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.

### CODE REVIEW

**Review by baptiste-b-pegasys — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
👍

**Review by bgravenorst — APPROVED** [review]

**Review by pinges — APPROVED** [review]

**Review by usmansaleem — APPROVED** [review]
👍🏼

**Review by macfarla — APPROVED** [review]

**Review by jframe — APPROVED** [review]

**Review by MadelineMurray — APPROVED** [review]

**Review by garyschulte — APPROVED** [review]
:+1:

**Review by jflo — APPROVED** [review]

**Review by ajsutton — APPROVED** [review]

**Review by lucassaldanha — APPROVED** [review]

**Comment by vmichalik** [comment]
As we've hit 13/25 we are at a majority, merging!

**Pull request merged**
