### PR TITLE
add profile info to help footer

### LINKED ISSUE #6430: Add profiles info in the besu help footer
At least a note that says "for more info go here" with a link to docs

See Pico CLI help API here https://picocli.info/#_usage_help_api

### PR DESCRIPTION
**Pull request by macfarla**
fixes #6430 

depends on #6449

### CODE REVIEW

**Comment by macfarla** [comment]
@non-fungible-nelson what do you think of adding this to the footer of the help message?

**Comment by non-fungible-nelson** [comment]
For Matt: --network to get started and a profile... note the JWT and connect CL to sync yadda yadda

**Comment by macfarla** [comment]
Updated based on your comments @non-fungible-nelson 
Screenshot 2024-02-09 at 11 15 54 am

**Comment by macfarla** [comment]
```
➜  besu git:(help-footer-profiles) ✗ ./build/install/besu/bin/besu --network=mainnet --profile=minimalist_staker
2024-02-09 11:25:15.045+10:00 | main | INFO  | Besu | Starting Besu
2024-02-09 11:25:16.221+10:00 | main | WARN  | Besu | Engine API authentication enabled without key file. Expect ephemeral jwt.hex file in datadir
2024-02-09 11:25:16.230+10:00 | main | INFO  | Besu | Connecting to 0 static nodes.
2024-02-09 11:25:16.409+10:00 | main | INFO  | Besu |
####################################################################################################
#                                                                                                  #
# Besu version 24.1.2-dev-e8f72840                                                                 #
#                                                                                                  #
# Configuration:                                                                                   #
# Network: Mainnet                                                                                 #
# Network Id: 1                                                                                    #
# Profile: Minimalist staker                                                                       #
# Data storage: Bonsai                                                                             #
# Sync mode: Checkpoint                                                                            #
# Engine APIs: ENGINE,ETH                                                                          #
# Engine port: 8551                                                                                #
# Engine JWT: /Users/sm/workspace/besu/build/install/besu/jwt.hex                                  #
# Using LAYERED transaction pool implementation                                                    #
# Using STACKED worldstate update mode                                                             #
#                                                                                                  #
# Host:                                                                                            #
# Java: openjdk-java-17                                                                            #
# Maximum heap size: 24.00 GB                                                                      #
# OS: osx-x86_64                                                                                   #
# Total memory: 96.00 GB                                                                           #
# CPU cores: 12                                                                                    #
#                                                                                                  #
####################################################################################################
```

**Comment by non-fungible-nelson** [comment]
LGTM 🚢

**Review by Gabriel-Trintinalia — APPROVED** [review]

**Pull request merged**
