### PR TITLE
deprecation: replace calls to isEqualToComparingFieldByField 

### PR DESCRIPTION
**Pull request by macfarla**
with usingRecursiveComparison().isEqualTo

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Simple find and replace. 

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by antonydenyer — APPROVED** [review]
LGTM

https://github.com/hyperledger/besu/issues/2766

**Review by shemnon — APPROVED** [review]
LGTM, pending some reversal based on unit and integration tests.

**Comment by macfarla** [comment]
@atoulme Q for you -
the test failures here - a lot of them boil down to this problem - is this something to address in tuweni? I can't really see a nice way around it at the besu end. 
```
field/property 'payload.unsignedPayload.digest.delegate' differ:
- actual value  : 0xb58e0d975ca2e178b705d7c5a5ee243f51b7d8449097746bb93a47f17392ff85 (ArrayWrappingBytes32@f09a29b)
- expected value: 0xb58e0d975ca2e178b705d7c5a5ee243f51b7d8449097746bb93a47f17392ff85 (ByteBufferWrappingBytes32@1afb8449)
org.apache.tuweni.bytes.ArrayWrappingBytes32 can't be compared to org.apache.tuweni.bytes.ByteBufferWrappingBytes32 as ByteBufferWrappingBytes32 does not declare all ArrayWrappingBytes32 fields, it lacks these: [bytes]
```
or this one which I think is the inverse of ^
`org.apache.tuweni.bytes.ByteBufferWrappingBytes32 can't be compared to org.apache.tuweni.bytes.ArrayWrappingBytes32 as ArrayWrappingBytes32 does not declare all ByteBufferWrappingBytes32 fields, it lacks these: [byteBuffer]`

**Comment by atoulme** [comment]
Not sure I can help much here - equality works:
`    assertEquals(new ArrayWrappingBytes32(new byte[32]), new ByteBufferWrappingBytes32(ByteBuffer.allocate(32)));`

These are different implementations of the Bytes object, one with a native byte array, and one with a ByteBuffer backing it. I am not sure what the effort here is, but if you try to compare the fields of the object, it won't work here.

**Pull request merged**
