### PR TITLE
Emeritus maintainers x 2

### PR DESCRIPTION
**Pull request by macfarla**
I propose moving the following maintainers to Emeritus status, pursuant to the inactivity clause. These maintainers have had no activity during Q3/Q4 2021 (since July 2021):
* @mbaxter’s last Besu activity was in July 2021
* @abdelhamidbakhta’s last Besu activity was in July 2021

We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly project. If any of these maintainers express in this PR that they intend to make contributions in the next quarter, then they will not be moved to emeritus status.
This vote is open until either an absolute majority of active maintainers votes for the same outcome, or until two weeks has passed, after which a voting majority will determine the outcome (with a tie resulting in no change).

### CODE REVIEW

**Review by fab-10 — APPROVED** [review]

**Comment by abdelhamidbakhta** [comment]
> I propose moving the following maintainers to Emeritus status, pursuant to the inactivity clause. These maintainers have had no activity during Q3/Q4 2021 (since July 2021):
> 
> * @mbaxter’s last Besu activity was in July 2021
> * @abdelhamidbakhta’s last Besu activity was in July 2021
> 
> We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly project. If any of these maintainers express in this PR that they intend to make contributions in the next quarter, then they will not be moved to emeritus status. This vote is open until either an absolute majority of active maintainers votes for the same outcome, or until two weeks has passed, after which a voting majority will determine the outcome (with a tie resulting in no change).

Hey,
I intend to make contributions in the next quarter.

**Review by antonydenyer — APPROVED** [review]

**Review by matkt — CHANGES_REQUESTED** [review]
it seem to me early to remove them. In addition, @abdelhamidbakhta  will continue to contribute

**Review by matkt — APPROVED** [review]

**Comment by macfarla** [comment]
Great to hear @abdelhamidbakhta - I've made that change to add you back in to active maintainers. 
@matkt do you think the waiting period needs to be extended (currently it says a quarter of inactivity) - let's discuss in contributors channel!
@mbaxter reach out if you still want to be involved :)

**Comment by matkt** [comment]
> Great to hear @abdelhamidbakhta - I've made that change to add you back in to active maintainers. @matkt do you think the waiting period needs to be extended (currently it says a quarter of inactivity) - let's discuss in contributors channel! @mbaxter reach out if you still want to be involved :)

I think we can talk about it during the contributor call or just ping people like now to know if they plan to contribute

**Comment by macfarla** [comment]
> I think we can talk about it during the contributor call or just ping people like now to know if they plan to contribute

ok I've put it on the agenda for the contributor call :)

**Comment by mbaxter** [comment]
I do plan to keep contributing - I have a PR open in draft that has been sitting for too long, but I actually just started to pick it back up and will try to get that merged in soon 🤞

**Comment by macfarla** [comment]
> I do plan to keep contributing - I have a PR open in draft that has been sitting for too long, but I actually just started to pick it back up and will try to get that merged in soon 🤞

Awesome news @mbaxter :)

OK closing this PR - thanks all!

**Pull request closed without merging**
