### PR TITLE
[TESTING] remove junit4 dependency

### LINKED ISSUE #5555: Migrate tests from Junit4 to Junit5
This is a decent resource to explain the differences https://blogs.oracle.com/javamagazine/post/migrating-from-junit-4-to-junit-5-important-differences-and-benefits

There are a lot of tests so breaking it down by module.

### LINKED ISSUE #7742: Remove junit 4 dependencies
Confirm that all tests have been migrated to Junit5
Then can remove junit 4 dependencies
(follow on from #7348 )

### PR DESCRIPTION
**Pull request by macfarla**
## Fixed Issue(s)
fixes #7742 
fixes #5555

### Thanks for sending a pull request! Have you done the following?

- [ ] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by pinges — APPROVED** [review]
LGTM

**Review by siladu — APPROVED** [review]
🎉

**Review by siladu — COMMENTED** [review]
Can it be removed from here too ? https://github.com/hyperledger/besu/blob/main/platform/build.gradle#L112

**Comment by fab-10** [comment]
all the occurrences of `org.junit.vintage:junit-vintage-engine` should be removed as well

**Review by fab-10 — APPROVED** [review]

**Pull request merged**
