### PR TITLE
remove --host-whitelist option issue #7761

### PR DESCRIPTION
**Pull request by JanetMo**
remove the --host-whitelist option, issue #7761

deleted the command and it's associated tests, we however did not manage to test / build 
(unfortunately, automatically added some beauty changes in benchmark/docker-compose.yml)

### CODE REVIEW

**Comment by macfarla** [comment]
@JanetMo thanks for your PR - you should be able to revert the changes to the docker-compose file to remove that from this PR. Also I think RetestethSubCommand has been deleted in the meantime, so you've got a conflict there

**Review by macfarla — COMMENTED** [review]
don't forget to add a changelog entry - even though it's been deprecated for ages, this is a BREAKING change

**Comment by JanetMo** [comment]
Thanks @macfarla for the update! We reverted the changes to the docker-compose file and solved the merge conflict, we weren't able to signoff some of the commits though. Do you have an idea, how to sign previous commits (we tried to rebase)?

The changelog was already updated previously by @jflo I believe.

**Comment by jflo** [comment]
details on how to correct a DCO situation can be found on the failing DCO action:

https://github.com/hyperledger/besu/pull/7847/checks?check_run_id=32756293076

**Comment by JanetMo** [comment]
@jflo Thanks for the help. We tried rebasing, but it seems to have made it worse.... Should I just start over with a fresh PR?

**Comment by JanetMo** [comment]
@macfarla @jflo We created a fresh PR https://github.com/hyperledger/besu/pull/7884
Sorry for the confusion and thanks for the help so far!

**Pull request closed without merging**
