### PR TITLE
Show correct revert reason data in priv_call

### PR DESCRIPTION
**Pull request by NickSneo**
## PR description
priv_call was showing incorrect error -"invalid params" even when execution is reverted. PR fixes to show correct error - "REVERT_ERROR" and show correct revert reason data

## Fixed Issue(s)
https://github.com/hyperledger/besu/issues/5223

### CODE REVIEW

**Comment by NickSneo** [comment]
@macfarla Hey Sally, can you please review this?

**Review by macfarla — COMMENTED** [review]
looks good to me. @NickSneo can you add a changelog entry for this please

**Review by pinges — APPROVED** [review]
LGTM

**Comment by macfarla** [comment]
the CI failures are network related so should be fixed on re-run

**Comment by NickSneo** [comment]
> looks good to me. @NickSneo can you add a changelog entry for this please

Sure adding changelog entry for this

**Comment by non-fungible-nelson** [comment]
Let's get this 🚢 for 23.4.0 ! @macfarla

**Pull request merged**
