### PR TITLE
Bugfix potential chain head and worldstate inconsistency

### PR DESCRIPTION
**Pull request by garyschulte**
## PR description
Ensure we do not leave the bonsai database in an inconsistent state where chain head and worldstate are at different block hashes

## Fixed Issue(s)

relates to #4784

## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by shemnon — APPROVED** [review]
LGTM

**Comment by AegeanDad** [comment]
When do you expect to release this patch to stakers? As it stands, I am down.

**Comment by garyschulte** [comment]
> When do you expect to release this patch to stakers? As it stands, I am down.

This PR does not purport to fix the underlying cause of #4784, but just mitigates the database damage from a failed fork-choice update if/when it occurs.  For now the only recourse if you encounter the defect in 4784 is to resync besu.

**Comment by AegeanDad** [comment]
Given that this data issue pertains to a specific block (0x3bc82334b7902026f2e9ed64122ccf224899f014dc25823a8b30568e588f20cd, block 16243159) in my case, would you be able to recommend a quicker data fix that targets the specific block in the database?

**Comment by garyschulte** [comment]
> Given that this data issue pertains to a specific block (0x3bc82334b7902026f2e9ed64122ccf224899f014dc25823a8b30568e588f20cd, block 16243159) in my case, would you be able to recommend a quicker data fix that targets the specific block in the database?

sent a private DM on discord.  It is non-trivial to recover a database from this state.

**Pull request merged**
