### PR TITLE
checkpoint sync for merge

### PR DESCRIPTION
**Pull request by matkt**
Signed-off-by: Karim TAAM <karim.t2am@gmail.com>

## PR description
For the merge the block of the checkpoint must not be after the deployment of the deposit contract 
## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by daniellehrner — APPROVED** [review]
LGTM

**Review by garyschulte — APPROVED** [review]
👍   

as an aside: it would be nice to be able to override the checkpoint params on the cli.  right now we cannot have a map override type so we cannot override either the discovery or checkpoint config items

**Comment by matkt** [comment]
I did a quick optimisation for the sync. if you can review it @garyschulte @fab-10

**Comment by matkt** [comment]
result of my tests with this new checkpoint block on i3.2xlarge
- 24 hours for mainnet
- 3 hours 45 minutes for goerli 
this new sync will be ready for the merge

**Review by garyschulte — APPROVED** [review]
👍

**Pull request merged**
