### PR TITLE
Add revert reason to trace calls

### PR DESCRIPTION
**Pull request by davemec**
## PR description
Add revert reason to trace calls

## Fixed Issue(s)
#695 

## Changelog

- [X] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by shemnon** [comment]
Do none of the current trace tests that test reverts (.../ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs) have a revert reason?

**Comment by shemnon** [comment]
Looks like bloc 0x12 of the trace series does have a revert reason (search for `0x7d88c1856cc95352`).  Is this where we would have expected it to show up?

**Comment by davemec** [comment]
> Do none of the current trace tests that test reverts (.../ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/specs) have a revert reason?

The TraceReplayblockTransactions code does have tests but it was already completed and not changed by this PR. Are you saying you prefer the json tests to the the unit test I created?

**Comment by davemec** [comment]
> Looks like block 0x12 of the trace series does have a revert reason (search for `0x7d88c1856cc95352`). Is this where we would have expected it to show up?

I will add a contract test.

**Review by shemnon — APPROVED** [review]

**Pull request merged**
