### PR TITLE
p2p/config: update classic testnet bootnodes

### PR DESCRIPTION
**Pull request by soc1c**
## PR description

updates kotti bootnodes

updates mordor bootnodes

### CODE REVIEW

**Comment by shemnon** [comment]
The commits require a valid DCO field.  Because I specifically know you I'll be satisfied with your github username and a functioning e-mail address.

**Comment by soc1c** [comment]
I no longer hold the credentials for this account. Unless there is a way to do this in the Github UI, this contribution would be lost.

**Comment by shemnon** [comment]
The requirement for a signed-off-by line in the commits themselves is a hard requirement, one I can't waive.  If correcting this would involve a new PR with a new github account and closing this one that is fine (so long as I know it is you).

**Comment by shemnon** [comment]
These changes were incorporated in PR #366

**Pull request closed without merging**
