### PR TITLE
replace ArrayList with HashSet for rpcMethodExists check

### PR DESCRIPTION
**Pull request by thinkAfCod**
## PR description
When executing the RpcMethod.rpcMethodExists(String rpcMethod) method, using HashSet instead of ArrayList provides a very very small performance improvement of a few nanoseconds. 😂😂

## Fixed Issue(s)
nothing

### CODE REVIEW

**Comment by macfarla** [comment]
@thinkAfCod you need to add signoff to your commits to make the DCO happy.

**Review by siladu — APPROVED** [review]
LGTM, good spot

**Review by fab-10 — COMMENTED** [review]
will be nice to have a micro benchmark to understand the improvement

**Comment by macfarla** [comment]
> will be nice to have a micro benchmark to understand the improvement

@thinkAfCod do you have numbers from your testing that you could add to evidence to support the improvement?

**Review by shemnon — APPROVED** [review]

**Comment by shemnon** [comment]
Design wise a O(ln) lookup is better than an O(n), so even without benchmarks I'm OK with this.  Whether we will see improvement in typical use cases is a valid question, but some cases with broken clients they may come to the conclusion their RPCs will fail quicker so they can increase the TPS of calls they should know fail.

**Pull request merged**
