### PR TITLE
Add Diego López León to maintainers

### PR DESCRIPTION
**Pull request by atoulme**
Signed-off-by: Antoine Toulme <antoine@lunar-ocean.com>

## PR description

Diego has made significant [commits](https://github.com/hyperledger/besu/pulls?q=is%3Apr+author%3Adiega) improving the quality and features of besu, this PR adds him as a maintainer.

Voting ends 2 weeks from the publication of this PR or once a majority of the maintainers vote.

For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by garyschulte — APPROVED** [review]
🚢  !

**Review by macfarla — APPROVED** [review]

**Review by daniellehrner — APPROVED** [review]

**Review by taccatisid — APPROVED** [review]

**Review by jflo — APPROVED** [review]

**Review by lucassaldanha — APPROVED** [review]

**Comment by diega** [comment]
Hey! Thanks @atoulme for the proposal and thanks to everyone who voted for their trust in me. I am more than happy to take on the responsibilities associated with this role.

**Review by pinges — APPROVED** [review]

**Review by jframe — APPROVED** [review]

**Review by antonydenyer — APPROVED** [review]

**Review by usmansaleem — APPROVED** [review]
👍🏼

**Review by matkt — APPROVED** [review]

**Review by shemnon — APPROVED** [review]

**Review by sajz — APPROVED** [review]

**Comment by garyschulte** [comment]
This PR has met the more than 50% threshold, merging it ahead of the 2 week cutoff.  Congrats @diega  🥳

**Comment by atoulme** [comment]
Did you actually commit the change @garyschulte ?

**Comment by garyschulte** [comment]
I set it to automerge 🤔

**Pull request merged**
