### PR TITLE
[MAINTAINERS] new non-code maintainers

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

I propose adding Helen George and Matt Nelson to Besu non-code maintainers. They have started helping manage, categorize bugs and other Github issues for Besu, as well as collaborating with the existing maintainers to help coordinate the development and roadmap planning of Besu.

Becoming non-code maintainers, they will be able to label bugs and close relevant tickets, helping to keep the project tidy.

Voting ends two weeks from today.

For more information on this process see the Becoming a non-code Maintainer section in the MAINTAINERS.md file.

### CODE REVIEW

**Review by pinges — APPROVED** [review]

**Review by daniellehrner — APPROVED** [review]

**Review by garyschulte — APPROVED** [review]

**Review by fab-10 — APPROVED** [review]

**Review by frankisawesome — APPROVED** [review]

**Review by siladu — APPROVED** [review]

**Review by atoulme — APPROVED** [review]

**Review by usmansaleem — APPROVED** [review]
LGTM

**Review by rolfyone — APPROVED** [review]

**Review by antonydenyer — APPROVED** [review]

**Review by shemnon — CHANGES_REQUESTED** [review]
This was discussed on the 10 May contributor call but all my comments were not added to the written notes - https://wiki.hyperledger.org/display/BESU/2022-05-10+Contributor+Call
I had some questions on the last non-code maintainers request and the request was closed rather than getting a full resolution on my questions (https://github.com/hyperledger/besu/pull/3359)

Two main takeaways:
(a) The besu-triage group allows members of that group to fully manage issues without granting the "maintain" privileges that code maintainers have. Membership in granted simply by other maintainers vouching that they are employed in a position that needs such access.  Both Helen and Matt are in that group and currently have the needed permissions to work with zenhub, and it has been verified they can work as needed.

(b) This process is too heavyweight.  Given from (a) that people can get their jobs done the overhead of voting people in and listing them as maintainers is unneeded.  The hyperledger charter only requires a majority approval process for "Contributors who have the ability to approve pull requests or commit code and contributions directly to a project’s source code repository."  Since we don't need a heavyweight process I don't think we should use one.  A heavyweight process to add a maintainer also involves a heavyweight process to remove a maintainer, for example one who leaves the Besu ecosystem (with or without changing companies) or who leaves the roles that require the access (for example switching to the executive job ladder).

**Comment by shemnon** [comment]
So to be clear, my proposal is that instead of this processes PMs that need access are vouched by a maintainer they work with, and then access is granted. No voting, it's the reputation of the maintainer that is sufficient "social proof" for membership.

Removing access is similarly simple, a maintainer shares that the contributor is no longer in the role needing access and access is removed after confirming (or after reasonable effort to confirm has been performed) with the contributor being removed.

**Comment by macfarla** [comment]
Closing this in favor of a lightweight process for modifying the membership of the non-code contributors group

**Pull request closed without merging**
