### PR TITLE
Clear updated and deleted accounts after each commit

### PR DESCRIPTION
**Pull request by ahamlat**
## PR description
Clear updated and deleted accounts after each transaction commit.

**Block processing before this PR**
image

**Block processing with this PR**
image

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [x] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [x] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [x] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [x] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by matkt — APPROVED** [review]
LGTM

**Review by matkt — CHANGES_REQUESTED** [review]
need more tests regarding performance

**Review by matkt — APPROVED** [review]
LGTM

**Review by macfarla — APPROVED** [review]
LGTM

**Pull request merged**
