### PR TITLE
separate step for sonar

### PR DESCRIPTION
**Pull request by macfarla**
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

Separate SonarQube into its own step since it uses a restricted context

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by joshuafernandes — APPROVED** [review]
One more change I'd suggest @macfarla - in the workflow piece at the bottom of the page I'd set this to only run on the master branch similar to the dockerPublish job (ie it'll have all the rights to run things in the context)

**Comment by macfarla** [comment]
> One more change I'd suggest @macfarla - in the workflow piece at the bottom of the page I'd set this to only run on the master branch similar to the dockerPublish job (ie it'll have all the rights to run things in the context)

the advantage with that would be that it would always have the permissions to run - the disadvantage would be that the author of the PR may not look at the output

**Review by pinges — APPROVED** [review]
LGTM

**Comment by jflo** [comment]
I had issues in the past with trying it as a separate step, when remounting the project, the previous build wasn't there because it had run in a different executor. You might want to test that this generates test coverage correctly.

**Comment by macfarla** [comment]
closing this. tbh it hasn't been a problem since diego became a maintainer.

**Pull request closed without merging**
