### PR TITLE
[Issue 549] Update JSON-RPC over HTTP error responses to return 200 status code

### LINKED ISSUE #549: Update JSON-RPC over HTTP error responses to return 200 status code
JSON-RPC is supposed to be agnostic of what channel is being used. As per the 2.0 spec, there is no reason for using anything but 200 http status code whenever we are doing JSON-RPC over HTTP.

Also, returning 400 for valid JSON-RPC requests doesn't help when integrating with JSON-RPC clients.

Acceptance criteria

Any valid JSON-RPC request should generate a JSON-RPC response, the HTTP status code should be 200. No matter if the response is a success or error response.
Calling a method that hasn't been enabled or a method that doesn't exist are valid JSON-RPC requests, therefore the expected response is a JSON-RPC error (and status code = 200)
Any invalid JSON-RPC request (malformed json, etc) should generate a 400 status code.

### PR DESCRIPTION
**Pull request by gabrieledm**
## PR description

- Updated returned HTTP status code to 200 for JSON-RPC error
- Updated tests related to the modified HTTP status code

## Fixed Issue(s)

Fixes #549 

## Changelog

- [ ] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by shemnon** [comment]
The biggest issue is this is not a change we can introduce in a bi-weekly release.  This will need to be done on a quarterly release, and possibly paired with a SemVer major version bump, which requires some co-ordniation.  (on a separate thread I'm testing the waters for [CalVer](https://calver.org/) in rocket chat).

Next, Acceptance Tests are failing because of the new ways the errors come through Web3J, those need to be fixed.  This underscores why I consider it an API breaking change and hence not a bi-weekly change and the scope of the updates needed.

Finally, we need to introduce some tests that will induce the HTTP Error response.  I think poorly formed JSON and empty post bodies should be enough.

**Comment by shemnon** [comment]
Specifically in org.web3j.protocol.http.HttpService#performIO Web3J needs to throw exceptions when the HTTP Status code is 200 but the response object contains an error.

**Comment by gabrieledm** [comment]
I understand.
But the org.web3j.protocol.http.HttpService#performIO belongs to a library, so we have to modify the library itself ?
Regarding to Acceptance Tests i'm checking all the errors and trying to fix them.
After i will write tests for HTTP Error response.

**Comment by shemnon** [comment]
We would need to co-ordinate with them, as this would be a breaking change.  Posting a PR ourselves is the quickest path to victory.

**Comment by gabrieledm** [comment]
So it would be better if i delete this pull request ?

**Comment by shemnon** [comment]
Keep it open.

**Comment by gabrieledm** [comment]
Ok, for the moment i'll not work on it.
Thank you for the patience

**Comment by shemnon** [comment]
Issue was merged in as #1305, author was credited in git meta-data.

**Pull request closed without merging**
