### PR TITLE
Add process_release metric.

### PR DESCRIPTION
**Pull request by mcdee**
## PR description

Add a `process_release` metric containing release information.  This shows up as following:

```
process_release{version="besu/v22.4.1-dev-fe8ad2d5/linux-x86_64/openjdk-java-11",} 1.0
```

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by jflo — APPROVED** [review]
Thanks for the contrib!

**Comment by shemnon** [comment]
Metrics is the wrong place for this.  Long term it will increase the cardinality of the measures and really isn't a metric of operation.  This is more appropriate for log output, and is, in fact, already present in log outputs.

**Review by shemnon — CHANGES_REQUESTED** [review]
Metrics is the wrong place for this. Long term it will increase the cardinality of the measures and really isn't a metric of operation. This is more appropriate for log output, and is, in fact, already present in log outputs.

**Comment by mcdee** [comment]
@shemnon logs aren't easily available remotely, and commonly this sort of information leaves the logs relatively quickly as they rotate or are truncated.  All beacon nodes provide some form of this information in their metrics, and it has proven useful to be able to obtain information about the deployed version across multiple instances in larger operational environments.

As for the cardinality, we're talking 20-30 per year and this is insignificant compared to the volume of data being gathered elsewhere.

**Comment by shemnon** [comment]
Its a bad devops practice.  What is the measure of the gauge?  The real measure is coming through a label instead of the metric itself, the metric should be what is queried, not the labels.

> All beacon nodes provide some form of this information in their metrics
Can you provide concrete examples?

**Comment by influ7** [comment]
Thanks

**Pull request merged**
