### PR TITLE
Add container security scanning

### LINKED ISSUE #7154: GHA workflow for dockerscan
currently still running in CI
https://app.circleci.com/pipelines/github/hyperledger/besu/27763/workflows/fc96d628-5928-4bb0-ae50-b37b96b7ce57

from config.yml

```
  dockerScan:
    executor: trivy_executor
    steps:
      - checkout
      - restore_gradle_cache
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl bash
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan with trivy
          shell: /bin/sh
          command: |
            for FILE in $(ls docker)
            do
              if [[ $FILE == "test.sh" || $FILE == "tests" ]]; then
                continue
              fi
              docker pull -q "hyperledger/besu:develop-$FILE"
              trivy -q image --exit-code 1 --no-progress --severity HIGH,CRITICAL "hyperledger/besu:develop-$FILE"
            done
```

### PR DESCRIPTION
**Pull request by cdivitotawela**
## PR description
Container security scanning workflow added. This runs on schedule everyday. Also possible to run on-demand for a given image tag. This replace the CircleCI job running container scan daily. Schedule job only runs for the tag `develop`.

## Fixed Issue(s)
fixes #7154

### Thanks for sending a pull request! Have you done the following?

- [x] Checked out our [contribution guidelines](https://github.com/hyperledger/besu/blob/main/CONTRIBUTING.md)?
- [ ] Considered documentation and added the `doc-change-required` label to this PR [if updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).
- [ ] Considered the changelog and included an [update if required](https://wiki.hyperledger.org/display/BESU/Changelog).
- [ ] For database changes (e.g. KeyValueSegmentIdentifier) considered compatibility and performed forwards and backwards compatibility tests

### Locally, you can run these tests to catch failures early:

- [ ] unit tests: `./gradlew build`
- [ ] acceptance tests: `./gradlew acceptanceTest`
- [ ] integration tests: `./gradlew integrationTest`
- [ ] reference tests: `./gradlew ethereum:referenceTests:referenceTests`

### CODE REVIEW

**Review by usmansaleem — APPROVED** [review]
LGTM

**Review by joshuafernandes — APPROVED** [review]
LGTM

**Comment by macfarla** [comment]
should this PR also remove the CI job, or will we do that as a separate task @cdivitotawela (if the latter we should not close the issue with this PR)

**Comment by jflo** [comment]
fixes #3927 and #7126

**Pull request merged**
