### PR TITLE
Fix for forkId NPE.

### LINKED ISSUE #3343: Besu node crash with discovery-enabled=true in config.toml
### Description
As an user, I want to run up a Besu node with discovery-enabled set to true, but after a few errors, it crashes.
But when it is set to false, the errors continues but not crashes.

### Steps to Reproduce (Bug)
1.  Set discovery-enabled=true in config.toml.
2.  Set bootnodes array in config.toml.
2.  Start node.

**Logs** 

```2022-01-28 11:38:44.899+00:00 | main | DEBUG | Native | Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27 for /com/sun/jna/linux-x86-64/libjnidispatch.so
2022-01-28 11:38:44.902+00:00 | main | DEBUG | Native | Found library resource at jar:file:/data/alastria-node-besu/versionesBesu/besu-21.10.8/lib/jna-5.8.0.jar!/com/sun/jna/linux-x86-64/libjnidispatch.so
2022-01-28 11:38:44.905+00:00 | main | DEBUG | Native | Extracting library to /home/x281921/.cache/JNA/temp/jna4822194681370950143.tmp
2022-01-28 11:38:44.908+00:00 | main | DEBUG | Native | Trying /home/x281921/.cache/JNA/temp/jna4822194681370950143.tmp
2022-01-28 11:38:44.909+00:00 | main | DEBUG | Native | Found jnidispatch at /home/x281921/.cache/JNA/temp/jna4822194681370950143.tmp
2022-01-28 11:38:44.953+00:00 | main | DEBUG | NativeLibrary | Looking for library 'secp256k1'
2022-01-28 11:38:44.954+00:00 | main | DEBUG | NativeLibrary | Adding paths from jna.library.path: null
2022-01-28 11:38:44.954+00:00 | main | DEBUG | NativeLibrary | Trying libsecp256k1.so
2022-01-28 11:38:44.955+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libsecp256k1.so: cannot open shared object file: No such file or directory
2022-01-28 11:38:44.956+00:00 | main | DEBUG | NativeLibrary | Adding system paths: [/usr/lib/x86_64-linux-gnu, /lib/x86_64-linux-gnu, /lib64, /usr/lib, /lib, /usr/lib/x86_64-linux-gnu/libfakeroot]
2022-01-28 11:38:44.956+00:00 | main | DEBUG | NativeLibrary | Trying libsecp256k1.so
2022-01-28 11:38:44.957+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libsecp256k1.so: cannot open shared object file: No such file or directory
2022-01-28 11:38:44.957+00:00 | main | DEBUG | NativeLibrary | Looking for version variants
2022-01-28 11:38:44.961+00:00 | main | DEBUG | Native | Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27 for secp256k1
2022-01-28 11:38:44.963+00:00 | main | DEBUG | Native | Found library resource at jar:file:/data/alastria-node-besu/versionesBesu/besu-21.10.8/lib/secp256k1-0.4.2.jar!/linux-x86-64/libsecp256k1.so
2022-01-28 11:38:44.964+00:00 | main | DEBUG | Native | Extracting library to /home/x281921/.cache/JNA/temp/jna4489313619374674359.tmp
2022-01-28 11:38:44.973+00:00 | main | DEBUG | NativeLibrary | Found library 'secp256k1' at /home/x281921/.cache/JNA/temp/jna4489313619374674359.tmp
2022-01-28 11:38:45.009+00:00 | main | DEBUG | NativeLibrary | Looking for library 'eth_pairings'
2022-01-28 11:38:45.011+00:00 | main | DEBUG | NativeLibrary | Adding paths from jna.library.path: null
2022-01-28 11:38:45.011+00:00 | main | DEBUG | NativeLibrary | Trying libeth_pairings.so
2022-01-28 11:38:45.013+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libeth_pairings.so: cannot open shared object file: No such file or directory
2022-01-28 11:38:45.014+00:00 | main | DEBUG | NativeLibrary | Adding system paths: [/usr/lib/x86_64-linux-gnu, /lib/x86_64-linux-gnu, /lib64, /usr/lib, /lib, /usr/lib/x86_64-linux-gnu/libfakeroot]
2022-01-28 11:38:45.015+00:00 | main | DEBUG | NativeLibrary | Trying libeth_pairings.so
2022-01-28 11:38:45.015+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libeth_pairings.so: cannot open shared object file: No such file or directory
2022-01-28 11:38:45.016+00:00 | main | DEBUG | NativeLibrary | Looking for version variants
2022-01-28 11:38:45.019+00:00 | main | DEBUG | Native | Looking in classpath from jdk.internal.loader.ClassLoaders$AppClassLoader@5ffd2b27 for eth_pairings
2022-01-28 11:38:45.020+00:00 | main | DEBUG | Native | Found library resource at jar:file:/data/alastria-node-besu/versionesBesu/besu-21.10.8/lib/bls12-381-0.3.0.jar!/linux-x86-64/libeth_pairings.so
2022-01-28 11:38:45.022+00:00 | main | DEBUG | Native | Extracting library to /home/x281921/.cache/JNA/temp/jna5396103584728477048.tmp
2022-01-28 11:38:45.062+00:00 | main | DEBUG | NativeLibrary | Found library 'eth_pairings' at /home/x281921/.cache/JNA/temp/jna5396103584728477048.tmp
2022-01-28 11:38:45.065+00:00 | main | INFO  | Besu | Using LibEthPairings native alt bn128
2022-01-28 11:38:45.069+00:00 | main | INFO  | Besu | Using the native implementation of the signature algorithm
2022-01-28 11:38:45.076+00:00 | main | INFO  | Besu | Starting Besu version: besu/v21.10.8/linux-x86_64/openjdk-java-11
2022-01-28 11:38:45.125+00:00 | main | DEBUG | LoggerFactory | Using io.vertx.core.logging.Log4j2LogDelegateFactory
2022-01-28 11:38:45.163+00:00 | main | DEBUG | ResourceLeakDetector | -Dio.netty.leakDetection.level: simple
2022-01-28 11:38:45.164+00:00 | main | DEBUG | ResourceLeakDetector | -Dio.netty.leakDetection.targetRecords: 4
2022-01-28 11:38:45.188+00:00 | main | DEBUG | PlatformDependent0 | -Dio.netty.noUnsafe: false
2022-01-28 11:38:45.189+00:00 | main | DEBUG | PlatformDependent0 | Java version: 11
2022-01-28 11:38:45.192+00:00 | main | DEBUG | PlatformDependent0 | sun.misc.Unsafe.theUnsafe: available
2022-01-28 11:38:45.193+00:00 | main | DEBUG | PlatformDependent0 | sun.misc.Unsafe.copyMemory: available
2022-01-28 11:38:45.195+00:00 | main | DEBUG | PlatformDependent0 | java.nio.Buffer.address: available
2022-01-28 11:38:45.196+00:00 | main | DEBUG | PlatformDependent0 | direct buffer constructor: available
2022-01-28 11:38:45.198+00:00 | main | DEBUG | PlatformDependent0 | java.nio.Bits.unaligned: available, true
2022-01-28 11:38:45.201+00:00 | main | DEBUG | PlatformDependent0 | jdk.internal.misc.Unsafe.allocateUninitializedArray(int): available
2022-01-28 11:38:45.202+00:00 | main | DEBUG | PlatformDependent0 | java.nio.DirectByteBuffer.<init>(long, int): available
2022-01-28 11:38:45.203+00:00 | main | DEBUG | PlatformDependent | sun.misc.Unsafe: available
2022-01-28 11:38:45.204+00:00 | main | DEBUG | PlatformDependent | maxDirectMemory: 2086666240 bytes (maybe)
2022-01-28 11:38:45.205+00:00 | main | DEBUG | PlatformDependent | -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
2022-01-28 11:38:45.205+00:00 | main | DEBUG | PlatformDependent | -Dio.netty.bitMode: 64 (sun.arch.data.model)
2022-01-28 11:38:45.207+00:00 | main | DEBUG | PlatformDependent | -Dio.netty.maxDirectMemory: 2086666240 bytes
2022-01-28 11:38:45.207+00:00 | main | DEBUG | PlatformDependent | -Dio.netty.uninitializedArrayAllocationThreshold: 1024
2022-01-28 11:38:45.209+00:00 | main | DEBUG | CleanerJava9 | java.nio.ByteBuffer.cleaner(): available
2022-01-28 11:38:45.210+00:00 | main | DEBUG | PlatformDependent | -Dio.netty.noPreferDirect: false
2022-01-28 11:38:45.232+00:00 | main | DEBUG | MultithreadEventLoopGroup | -Dio.netty.eventLoopThreads: 4
2022-01-28 11:38:45.258+00:00 | main | DEBUG | InternalThreadLocalMap | -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
2022-01-28 11:38:45.258+00:00 | main | DEBUG | InternalThreadLocalMap | -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
2022-01-28 11:38:45.268+00:00 | main | DEBUG | NioEventLoop | -Dio.netty.noKeySetOptimization: false
2022-01-28 11:38:45.269+00:00 | main | DEBUG | NioEventLoop | -Dio.netty.selectorAutoRebuildThreshold: 512
2022-01-28 11:38:45.281+00:00 | main | DEBUG | PlatformDependent | org.jctools-core.MpscChunkedArrayQueue: available
2022-01-28 11:38:45.345+00:00 | main | DEBUG | DefaultDnsServerAddressStreamProvider | Default DNS servers: [/127.0.0.53:53] (sun.net.dns.ResolverConfiguration)
2022-01-28 11:38:45.355+00:00 | main | DEBUG | NetUtil | -Djava.net.preferIPv4Stack: false
2022-01-28 11:38:45.356+00:00 | main | DEBUG | NetUtil | -Djava.net.preferIPv6Addresses: false
2022-01-28 11:38:45.362+00:00 | main | DEBUG | NetUtilInitializations | Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
2022-01-28 11:38:45.367+00:00 | main | DEBUG | NetUtil | /proc/sys/net/core/somaxconn: 4096
2022-01-28 11:38:45.442+00:00 | main | INFO  | Besu | Static Nodes file = /data/alastria-node-besu/validator/static-nodes.json
2022-01-28 11:38:45.446+00:00 | main | INFO  | StaticNodesParser | StaticNodes file /data/alastria-node-besu/validator/static-nodes.json does not exist, no static connections will be created.
2022-01-28 11:38:45.449+00:00 | main | INFO  | Besu | Connecting to 0 static nodes.
2022-01-28 11:38:45.452+00:00 | main | INFO  | Besu | Security Module: localfile
2022-01-28 11:38:45.485+00:00 | main | INFO  | DatabaseMetadata | Lookup database metadata file in data directory: /data/alastria-node-besu/validator
2022-01-28 11:38:45.546+00:00 | main | INFO  | RocksDBKeyValueStorageFactory | Existing database detected at /data/alastria-node-besu/validator. Version 1
2022-01-28 11:38:45.925+00:00 | main | INFO  | KeyPairUtil | Loaded public key 0x0f41452bd52d269a9ab9174033ee632c1f17a27259a11003f7550840a5ad3beba07ec1126ff09f5f68649b54afb5de161fa3fc6f7eebdace04ae35f1845961fb from /data/alastria-node-besu/validator/keys/besu/key
2022-01-28 11:38:46.155+00:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [Byzantium: 0]
2022-01-28 11:38:46.340+00:00 | main | DEBUG | BesuPluginContextImpl | Plugin startup complete.
2022-01-28 11:38:46.346+00:00 | main | INFO  | RunnerBuilder | Detecting NAT service.
2022-01-28 11:38:46.379+00:00 | main | DEBUG | RlpxAgent | Using default NettyConnectionInitializer
2022-01-28 11:38:46.473+00:00 | main | INFO  | Runner | Starting Ethereum main loop ...
2022-01-28 11:38:46.474+00:00 | main | INFO  | MetricsHttpService | Starting metrics http service on 0.0.0.0:9545
2022-01-28 11:38:46.523+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.numHeapArenas: 4
2022-01-28 11:38:46.524+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.numDirectArenas: 4
2022-01-28 11:38:46.525+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.pageSize: 8192
2022-01-28 11:38:46.525+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.maxOrder: 11
2022-01-28 11:38:46.525+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.chunkSize: 16777216
2022-01-28 11:38:46.526+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.smallCacheSize: 256
2022-01-28 11:38:46.526+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.normalCacheSize: 64
2022-01-28 11:38:46.526+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.maxCachedBufferCapacity: 32768
2022-01-28 11:38:46.527+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.cacheTrimInterval: 8192
2022-01-28 11:38:46.527+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.cacheTrimIntervalMillis: 0
2022-01-28 11:38:46.527+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.useCacheForAllThreads: true
2022-01-28 11:38:46.528+00:00 | main | DEBUG | PooledByteBufAllocator | -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
2022-01-28 11:38:46.560+00:00 | main | DEBUG | DefaultChannelId | -Dio.netty.processId: 20372 (auto-detected)
2022-01-28 11:38:46.562+00:00 | main | DEBUG | DefaultChannelId | -Dio.netty.machineId: 00:0d:3a:ff:fe:ab:f3:13 (auto-detected)
2022-01-28 11:38:46.592+00:00 | main | DEBUG | ByteBufUtil | -Dio.netty.allocator.type: pooled
2022-01-28 11:38:46.593+00:00 | main | DEBUG | ByteBufUtil | -Dio.netty.threadLocalDirectBufferSize: 0
2022-01-28 11:38:46.593+00:00 | main | DEBUG | ByteBufUtil | -Dio.netty.maxThreadLocalCharBufferSize: 16384
2022-01-28 11:38:46.613+00:00 | main | INFO  | NatService | No NAT environment detected so no service could be started
2022-01-28 11:38:46.614+00:00 | main | INFO  | NetworkRunner | Starting Network.
2022-01-28 11:38:46.613+00:00 | vert.x-eventloop-thread-1 | INFO  | MetricsHttpService | Metrics service started and listening on 9545:9545
2022-01-28 11:38:46.623+00:00 | nioEventLoopGroup-2-1 | INFO  | RlpxAgent | P2P RLPx agent started and listening on /0:0:0:0:0:0:0:0:30303.
2022-01-28 11:38:46.624+00:00 | main | INFO  | PeerDiscoveryAgent | Starting peer discovery agent on host=0.0.0.0, port=30303
2022-01-28 11:38:46.689+00:00 | vert.x-eventloop-thread-1 | INFO  | VertxPeerDiscoveryAgent | Started peer discovery agent successfully, on effective host=0:0:0:0:0:0:0:0 and port=30303
2022-01-28 11:38:46.692+00:00 | main | INFO  | PeerDiscoveryAgent | P2P peer discovery agent started and listening on /0:0:0:0:0:0:0:0:30303
2022-01-28 11:38:46.706+00:00 | main | ERROR | Runner | Startup failed java.lang.NullPointerException
2022-01-28 11:38:46.714+00:00 | Thread-1 | DEBUG | BesuPluginContextImpl | Plugin shutdown complete.
2022-01-28 11:38:46.728+00:00 | Thread-1 | ERROR | Besu | Failed to stop Besu
```

It shows this errors.

```
2022-01-28 11:38:45.011+00:00 | main | DEBUG | NativeLibrary | Trying libeth_pairings.so
2022-01-28 11:38:45.013+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libeth_pairings.so: cannot open shared object file: No such file or directory
2022-01-28 11:38:45.014+00:00 | main | DEBUG | NativeLibrary | Adding system paths: [/usr/lib/x86_64-linux-gnu, /lib/x86_64-linux-gnu, /lib64, /usr/lib, /lib, /usr/lib/x86_64-linux-gnu/libfakeroot]
2022-01-28 11:38:45.015+00:00 | main | DEBUG | NativeLibrary | Trying libeth_pairings.so
2022-01-28 11:38:45.015+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libeth_pairings.so: cannot open shared object file: No such file or directory
```
```
2022-01-28 11:38:44.954+00:00 | main | DEBUG | NativeLibrary | Trying libsecp256k1.so
2022-01-28 11:38:44.955+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libsecp256k1.so: cannot open shared object file: No such file or directory
2022-01-28 11:38:44.956+00:00 | main | DEBUG | NativeLibrary | Adding system paths: [/usr/lib/x86_64-linux-gnu, /lib/x86_64-linux-gnu, /lib64, /usr/lib, /lib, /usr/lib/x86_64-linux-gnu/libfakeroot]
2022-01-28 11:38:44.956+00:00 | main | DEBUG | NativeLibrary | Trying libsecp256k1.so
2022-01-28 11:38:44.957+00:00 | main | DEBUG | NativeLibrary | Loading failed with message: libsecp256k1.so: cannot open shared object file: No such file or directory
```

Then it crashes.
```
2022-01-28 11:38:46.706+00:00 | main | ERROR | Runner | Startup failed java.lang.NullPointerException
2022-01-28 11:38:46.714+00:00 | Thread-1 | DEBUG | BesuPluginContextImpl | Plugin shutdown complete.
2022-01-28 11:38:46.728+00:00 | Thread-1 | ERROR | Besu | Failed to stop Besu
```

### Versions (Add all that apply)
* Software version: 21.10.8
* Java version: openjdk 11.0.13

### PR DESCRIPTION
**Pull request by mark-terry**
Signed-off-by: Mark Terry <mark.terry@consensys.net>

## PR description
Fix for the case where an NPE is generated using legacy mode without non-zero milestone blocks.

## Fixed Issue(s)
Fixes #3343 

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by shemnon** [comment]
Putting Optional everywhere feels fairly high-touch.

Is there a copy of the null pointer exception stack trace?  I would like to see where the NPE is to get a feel for if such a wide changes is needed.

**Comment by shemnon** [comment]
Here's a more targeted fix - #3409

**Comment by mark-terry** [comment]
Bug report here: https://github.com/hyperledger/besu/issues/3343

I made the refactoring to `Optional` because the use of nulls (and the arising unexpected side effects) led to the NPE. Is there a reason nulls are preferred for this case?

**Comment by shemnon** [comment]
This fix only went part of the way with null forkIds, EthProtocolManager still used and reacted to a null ForkID. If we are going to switch to optional we should push it throughout the codebase, so that ForkIDs are either always returned or optionals are always used for ForkIDs.  Use both nulls and optionals increases the maintenance burden.

**Pull request closed without merging**
