### PR TITLE
Add Vijay Michalik to maintainers

### PR DESCRIPTION
**Pull request by atoulme**
Vijay has helped the Besu project through contributions to [user questions](https://chat.hyperledger.org/channel/besu?msg=pEvzRqPLYBvDtbX8m), documentation and [managing issues on the project](https://chat.hyperledger.org/channel/besu?msg=sazaeBhiNpY2Nc5Xk).

Voting ends 2 weeks from the publication of this PR.

For more information on this process see the Becoming a Maintainer section in the MAINTAINERS.md file.

## Approval of this PR

As for the maintainer addition, this PR being a significant change to the process, I require the same rules to be followed:

- [ ] 2 weeks voting period (ends June 3rd 2021)
- [x] at least 3 approvals
- [x] no veto
- [x] absolute majority makes it pass immediately (currently 11 approvals).

### CODE REVIEW

**Review by MadelineMurray — APPROVED** [review]

**Review by matkt — APPROVED** [review]

**Review by garyschulte — APPROVED** [review]
👍

**Review by NicolasMassart — APPROVED** [review]
Approved and I added this PR that may be interesting to review in parallel https://github.com/hyperledger/besu/pull/2307

**Review by RatanRSur — APPROVED** [review]

**Comment by shemnon** [comment]
From a process perspective #2307 needs to pass first, as without it there is insufficient justification in this PR.  Hence I vote block until either #2307 or a similar proposal passes. (to be explicit, if #2307 passes my block is removed).

**Review by macfarla — APPROVED** [review]

**Comment by macfarla** [comment]
@vmichalik has contributed variously and significantly to docs, Rocket Chat and support issues. Additionally triaging and organising GitHub issues.

**Review by pinges — APPROVED** [review]

**Review by ajsutton — APPROVED** [review]

**Review by usmansaleem — APPROVED** [review]
LGTM

**Review by jframe — APPROVED** [review]

**Comment by NicolasMassart** [comment]
Assuming @atoulme  is voting in favor, we reached 11 which is the absolute majority.

**Pull request merged**
