### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Thabokani**
## PR description

Fix typos in comments.

### CODE REVIEW

**Comment by macfarla** [comment]
@Thabokani thanks for your contribution - we can merge this if you add signoff to your commits - follow the instructions [here](https://github.com/hyperledger/besu/actions/runs/7690950701/job/20955512016?pr=6481) - to make the DCO check pass

**Comment by Thabokani** [comment]
> @Thabokani thanks for your contribution - we can merge this if you add signoff to your commits - follow the instructions [here](https://github.com/hyperledger/besu/actions/runs/7690950701/job/20955512016?pr=6481) - to make the DCO check pass

@macfarla thanks for your review. I have added signoff.

**Comment by macfarla** [comment]
ok one more thing to fix - I don't have permissions to update your branch otherwise I'd do it for you - but the plugin-api hash  needs updating - instructions here - that's why the unit tests are failing https://app.circleci.com/pipelines/github/hyperledger/besu/26758/workflows/0246a9b0-4020-414d-a270-3eb6027d82ba/jobs/176846

**Review by macfarla — APPROVED** [review]

**Comment by macfarla** [comment]
Thanks for persevering @Thabokani - should merge shortly!

**Pull request merged**
