### PR TITLE
Emeritus 

### PR DESCRIPTION
**Pull request by macfarla**
I propose moving the following maintainer to Emeritus status, pursuant to the inactivity clause. These maintainers have had no activity since September 2021:
* @vmichalik  - last Besu activity was in September 2021 #2718 

We very much appreciate their contributions but moving their status to emeritus (and thus revoking PR approval privileges) is in the interest of an orderly project. If any of these maintainers express in this PR that they intend to make contributions in the next quarter, then they will not be moved to emeritus status.
I propose this vote is open until either an absolute majority of active maintainers votes for the same outcome, or until two weeks has passed, after which a voting majority will determine the outcome (with a tie resulting in no change).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by matkt — APPROVED** [review]
LGTM

**Review by daniellehrner — APPROVED** [review]

**Review by fab-10 — APPROVED** [review]

**Review by jframe — APPROVED** [review]

**Comment by macfarla** [comment]
> Thanks @macfarla, happy to be moved. Hope all the team is doing well!

Hope you are doing well also @vmichalik!

**Comment by shemnon** [comment]
> Thanks @macfarla, happy to be moved. Hope all the team is doing well!

If @vmichalik consents to the move, is the vote needed?

**Comment by macfarla** [comment]
Since @vmichalik has given agreement, we can merge this change under the "Resignation of a maintainer" clause, which does not require majority vote. 

Thanks all!

**Pull request merged**
