### PR TITLE
Updated overview builder to consider networkId and custom network genesis.

### LINKED ISSUE #4880: options summary should say "custom genesis" if --genesis-file is used
When I start besu with a custom genesis file, the options printer outer prints "Mainnet" which could be misleading

eg here I have a custom genesis file (even using isQuorum mode) and it shows "Network: Mainnet"

```
2023-01-04 11:57:00.321+10:00 | main | INFO  | Besu | Starting Besu
2023-01-04 11:57:01.025+10:00 | main | WARN  | Besu | Discovery disabled: bootnodes will be ignored.
2023-01-04 11:57:01.026+10:00 | main | WARN  | Besu | isQuorum mode in genesis file (GoQuorum-compatible privacy mode) has been deprecated, use --privacy-enabled instead.
2023-01-04 11:57:01.031+10:00 | main | WARN  | Besu | Permissions are disabled. Cannot enable PERM APIs when not using Permissions.
2023-01-04 11:57:01.117+10:00 | main | INFO  | Besu |
####################################################################################################
#                                                                                                  #
# Besu 23.1.0-RC1-dev-3634d304                                                                     #
#                                                                                                  #
# Configuration:                                                                                   #
# Network: Mainnet                                                                                 #
```

### PR DESCRIPTION
**Pull request by mark-terry**
Signed-off-by: mark-terry <mark.terry@consensys.net>

## PR description
Enhances the Configuration Overview to include networkId and custom genesis files (when specified.)

## Fixed Issue(s)
Fixes #4880 

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if
    [updates are required](https://wiki.hyperledger.org/display/BESU/Documentation).

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Review by macfarla — APPROVED** [review]
needed one tiny fix to get the custom network id

**Comment by macfarla** [comment]
custom genesis output
```
# Configuration:                                                                                   #
# Network: Custom genesis file specified                                                           #
# Network Id: 2018        
```

**Comment by macfarla** [comment]
mainnet output
```
# Configuration:                                                                                   #
# Network: Mainnet                                                                                 #
# Network Id: 1                                                                                    #
```

**Comment by macfarla** [comment]
using --network
```
 besu --network sepolia
2023-01-19 14:35:35.405+10:00 | main | INFO  | Besu | Starting Besu
2023-01-19 14:35:35.707+10:00 | main | WARN  | Besu | Engine API authentication enabled without key file. Expect ephemeral jwt.hex file in datadir
2023-01-19 14:35:35.773+10:00 | main | INFO  | Besu |
####################################################################################################
#                                                                                                  #
# Besu 23.1.0-dev-6d8be27b                                                                         #
#                                                                                                  #
# Configuration:                                                                                   #
# Network: Sepolia                                                                                 #
# Network Id: 11155111
```

**Review by siladu — APPROVED** [review]
LGTM

**Review by Gabriel-Trintinalia — APPROVED** [review]
LGTM

**Pull request merged**
