### PR TITLE
Fix: Fallback to getName when canonicalName is null in BlockHeaderValidator DEBUG log

### LINKED ISSUE #6177: unhelpful log from BlockHeaderValidator: null rule failed
Noticed this validation failure (running on a private clique network) and the DEBUG message is "null rule failed" which comes from BlockHeaderValidator.applyRules

2023-11-17 09:56:56.903+10:00 | EthScheduler-Workers-0 | INFO  | TimestampMoreRecentThanParent | Invalid block header: timestamp 1670851110 is only 12 seconds newer than parent timestamp 1670851098. Minimum 15 seconds
2023-11-17 09:56:56.903+10:00 | EthScheduler-Workers-0 | DEBUG | BlockHeaderValidator | null rule failed

### PR DESCRIPTION
**Pull request by manojpramesh**
## PR description
When a validation rule fails in `BlockHeaderValidator`, debug message falls back to using just name when canonical name is not available.

## Fixed Issue(s)
Fixes #6177

### CODE REVIEW

**Review by macfarla — APPROVED** [review]

**Comment by manojpramesh** [comment]
@macfarla Thank you for the approval. Anything pending from my side to get this merged?

Also, what is the recommended approach to pull latest changes from main? Merge commit or rebase?

**Comment by macfarla** [comment]
@manojpramesh just catching up properly on things after the break - have you tested out that this works as you expect? This suggests that for inner classes getName might be the option that works https://stackoverflow.com/questions/15202997/what-is-the-difference-between-canonical-name-simple-name-and-class-name-in-jav

**Comment by macfarla** [comment]
> @macfarla Thank you for the approval. Anything pending from my side to get this merged?
> 
> Also, what is the recommended approach to pull latest changes from main? Merge commit or rebase?

personal preference on merge or rebase. I did hit merge on your PR though so you'll need to pull before you push

**Comment by manojpramesh** [comment]
Agree with using `getName` to include the `packageName` while logging. 

Here's the log when `canonicalName` is null after the fix. Since it's a lambda function, you can see it returns the counter generated during runtime - which I guess should be okay for a DEBUG log.

```
2024-01-08 23:02:21.016+08:00 | EthScheduler-Workers-0 | INFO  | TimestampMoreRecentThanParent | Invalid block header: timestamp 1704726141 is only 10 seconds newer than parent timestamp 1704726131. Minimum 15 seconds
2024-01-08 23:02:28.106+08:00 | EthScheduler-Workers-0 | DEBUG | BlockHeaderValidator | org.hyperledger.besu.ethereum.mainnet.BlockHeaderValidator$Builder$$Lambda$486/0x00000008004a5020 rule failed
```

**Review by macfarla — APPROVED** [review]

**Comment by macfarla** [comment]
Thanks for the contribution @manojpramesh

**Pull request merged**
