### PR TITLE
Support Version Rollbacks for RocksDB (#6)

### PR DESCRIPTION
**Pull request by RatanRSur**
## PR description
Primary:

This fixes an issue where rolling back the default database version could cause an error. It's important that the loading logic depends only on the database version so we can have full control. It's still fine to set auxiliary properties like isSegmentIsolationSupported as we go through the creation process.

Other:

Extend the plugin interface with Closeable

### CODE REVIEW

**Comment by shemnon** [comment]
This is a re-commit of PR #6

**Comment by RatanRSur** [comment]
@CjHare can you make a PR against my branch with your preferred email?

**Comment by RatanRSur** [comment]
@ryjones I'm still getting used to DCO practices but I is "Co-Authored-By" a DCO thing or just something github does that doesn't have any legal standing?

**Comment by ryjones** [comment]
> @ryjones I'm still getting used to DCO practices but is "Co-Authored-By" a DCO thing or just something github does that doesn't have any legal standing?

That line is a GitHub feature. That DCO bot doesn't handle it may or may not be a bug.

If the commit message could be changed from "Co-authored-by" to "Signed-off-by" with the correct email address in this case I will remove my -1

**Comment by RatanRSur** [comment]
When did DCO bot start running? If It was before PR #6 went up then it's definitely a bug as I'm using the same signoff process here as there.

**Pull request merged**
