### PR TITLE
Update tuweni2.4.2

### PR DESCRIPTION
**Pull request by atoulme**
## PR description
Update Tuweni to 2.4.2.

### CODE REVIEW

**Comment by atoulme** [comment]
@macfarla I have finally found time to resolve the fix with DNS discovery and release a new version.

**Comment by macfarla** [comment]
ref #5585 and #5627

**Comment by macfarla** [comment]
@atoulme seeing a few errors like this on startup - is this expected? 
```
{"@timestamp":"2023-07-11T04:31:42,333","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with M6GXUJE32FMP35VTJD37EV.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:42,543","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with FWCA7KXXGTJWVX27HUSMX3.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:42,732","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with 62DU4SUPD7MMO7VQATDPGH.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:42,851","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with IKU3FLD2Y6ZQPPWC7JJTIF.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,051","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with NZBS36OLS6ZTV76VT5ONUQ.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,180","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with UHCXMU25WTLXLVS5IN2KRW.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,310","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with A5UYGNBJHPZBZMXM3IHVN5.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,430","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with K5XW2QWGDWL3RXIFEVJLFM.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsExcepti
on: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,499","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with H3IFD4JUIAWDQ5WEJMEIDP.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,626","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with N5AOB3PDDSA5OTV4PMYNPH.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,747","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with N55M2VSLFWKSXZZKEJR4MQ.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,847","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with FJYHG5KVZEXUZGVM6AZDDG.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:43,967","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with BHQRICPKVMBGCUVO6LKWJY.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
{"@timestamp":"2023-07-11T04:31:44,097","level":"WARN","thread":"vert.x-eventloop-thread-3","class":"DNSResolver","message":"DNS query error with FYNI6NSH36P4Q4RYPVVUFY.all.goerli.ethdisco.net","throwable":" io.vertx.core.dns.DnsException: DNS query error occurred: NXDOMAIN: type 3, name error\n"}
```

**Comment by atoulme** [comment]
The warnings indicate that the DNS tree has invalid, missing entries. I think that’s not on us, but the tree will always have some.

We can follow up with better error reporting perhaps. Do you want to silence those warnings?

**Comment by macfarla** [comment]
> The warnings indicate that the DNS tree has invalid, missing entries. I think that’s not on us, but the tree will always have some.
> 
> We can follow up with better error reporting perhaps. Do you want to silence those warnings?

I'd rather not silence them. They only appear at startup.

**Review by macfarla — APPROVED** [review]

**Comment by siladu** [comment]
> > The warnings indicate that the DNS tree has invalid, missing entries. I think that’s not on us, but the tree will always have some.
> > We can follow up with better error reporting perhaps. Do you want to silence those warnings?
> 
> I'd rather not silence them. They only appear at startup and then periodically when refreshing. Would be good to have a better error message but I think we don't need to wait for that.

If it's expected that the tree always has some and these are not WARNs that the user can or should act on then I think they belong at DEBUG level.

**Pull request merged**
