### PR TITLE
Migrate plugins module to Junit 5.0

### PR DESCRIPTION
**Pull request by 7suyash7**
Migrate the plugins module from JUnit 4.0 to JUnit 5.0\
#5559

### CODE REVIEW

**Comment by macfarla** [comment]
```
error: cannot access Ignore
  class file for org.junit.Ignore not found
1 error
```
In JUnit 5 it's `Disable` https://junit.org/junit5/docs/current/user-guide/#writing-tests-disabling

**Comment by macfarla** [comment]
@7suyash7 I couldn't assign the ticket to you so have assigned to myself just so no-one else picks it up. Let me know if you're stuck on this one! And thanks for your contribution!

**Comment by 7suyash7** [comment]
@macfarla I know its `@Disable`, however I'm not using `Disable` or `Ignore` in any of the test cases in plugins...

**Comment by macfarla** [comment]
> @macfarla I know its `@Disable`, however I'm not using `Disable` or `Ignore` in any of the test cases in plugins...

Right - it's because of the superclass AbstractKeyValueTest which is in a different module - once this is merged #5613 that should go away

**Comment by macfarla** [comment]
closed in favour of #5703

**Pull request closed without merging**
