### PR TITLE
Prioritize High Gas Price Transactions

### LINKED ISSUE #1285: Order Transactions By Gas Price and then By Time Added To Pool
To prevent transaction spamming, most clients are implementing a FIFO ordering among transactions with the same gas price. From the code below, it looks like we already do that. However, it seems like we don't order by gas price, which is a problem for maximizing mining profits.

https://github.com/hyperledger/besu/blob/7b9ade23cde145e67f90112d3411e80f860129f6/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java#L72-L76

### Acceptance Criteria
Ensure that we order by gas price and then by time. If we don't do either, implement and test.

### PR DESCRIPTION
**Pull request by RatanRSur**
### Fixed Issue(s)
fixes #1285 

### Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### Credit
credit to @JoshMelton for initial work.

### CODE REVIEW

**Review by abdelhamidbakhta — APPROVED** [review]
Looks good to me.
Only reviewed the code on Github.
Did you do manual testing as well ?

**Comment by RatanRSur** [comment]
Maybe once I fix the unit tests I broke I can think about that 😅

**Comment by RatanRSur** [comment]
@abdelhamidbakhta Fixed the unit tests.

I didn't do any manual testing but I personally feel comfortable with the unit test coverage. Let me know if you don't think that's sufficient :)

**Comment by RatanRSur** [comment]
@NicolasMassart @MadelineMurray [told me to ping y'all](https://github.com/hyperledger/besu/issues/1285#issuecomment-671097432) when this is addressed. We now drop the remote, lowest gas-price, oldest transaction. Before we just sorted by remote and oldest.

**Pull request merged**
