### PR TITLE
Handle hadolint check failure with proper risk assessment

### PR DESCRIPTION
**Pull request by pullurib**
## PR description
Suppressing/Ignoring hadolint warning about the last USER in Dockerfile being the root user - with reasoning that the root user has very specific job to do and then besu runs as besu user . 

Follow up to https://github.com/hyperledger/besu/pull/7575

## Fixed Issue(s)
Follow up fix to #4292

### CODE REVIEW

**Review by fab-10 — APPROVED** [review]

**Comment by fab-10** [comment]
Still something not working https://github.com/hyperledger/besu/actions/runs/10927512262/job/30333865457 seems related to `testDocker` task

**Comment by pullurib** [comment]
Looking into it, that gradle task runs fine locally on my Mac

**Comment by fab-10** [comment]
Running it on Linux we get this report

```
<testcase name="File /var/lib/besu owner" time="0.000">
<system-err>File: /var/lib/besu: owner: Expected &#34;root&#34; to equal &#34;besu&#34;</system-err>
<failure>File: /var/lib/besu: owner: Expected &#34;root&#34; to equal &#34;besu&#34;</failure>
</testcase>
```

the expected user does not match

**Comment by fab-10** [comment]
Fix for the CI issue https://github.com/hyperledger/besu/pull/7655

**Comment by pullurib** [comment]
@fab-10 Thanks for taking care of it. I wasn't able to repro with act runs and was planning on uploading the reports to see what was failing. This is a better approach to wait for besu that waiting a few seconds .

**Pull request merged**
