### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by ryjones**
## PR description

Creating a valid CODEOWNERS file

### CODE REVIEW

**Review by shemnon — CHANGES_REQUESTED** [review]
Why do we need to do this?  The last time we did this it flooded all our github inboxes with literally every PR.

**Comment by ryjones** [comment]
@shemnon 
> Why do we need to do this? The last time we did this it flooded all our github inboxes with literally every PR.

I went through a bunch of branch rules; none of them had "require code owner reviews". The reason to do this is for some PR automation. @jflo ?

**Comment by shemnon** [comment]
Has github changed automation that will then add all the codeowners as a designated reviewer to every single PR? That's what happend last time we tried to turn it on.

If it's not absolutely needed for github actions I don't want to have to dismiss every besu PR that gets posted from my github inbox.

**Comment by jflo** [comment]
We don't need CODEOWNERS for anything related to a GHA based CI/CD pipeline.  Happy to research adopting it in the future, but it is not needed.

**Pull request closed without merging**
