### PR TITLE
Use github arm64 runners

### LINKED ISSUE #7026: Migrate from self-hosted hyp-ci-linux-arm64 to besu-arm64 runner
For arm docker builds we currently target the self-hosted `hyp-ci-linux-arm64` but now there is a github provided runner enabled

### PR DESCRIPTION
**Pull request by seanyoung**
github now offer arm64 runners.

The arm64 image is a plain ubuntu 22.04 server with nothing installed (no docker).

Fixes  #7026

### CODE REVIEW

**Review by siladu — DISMISSED** [review]
Thanks for the PR @seanyoung. LGTM but think we should wait to merge this until we've completed the in-flight release. 

Am trying to test that at least the docker install works, but it's stuck waiting, not sure if that's expected...it did trigger with the correct runner, but maybe it's stuck because it's on my fork https://github.com/siladu/besu/actions/runs/8978675974/job/24659493468

**Review by siladu — APPROVED** [review]
Thanks for the PR @seanyoung. Were you able to test the docker changes?

I am trying to test that at least the docker install works, but it's stuck waiting, not sure if that's expected...it did trigger with the correct runner, but maybe it's stuck because it's on my fork [siladu/besu/actions/runs/8978675974/job/24659493468](https://github.com/siladu/besu/actions/runs/8978675974/job/24659493468)

**Comment by seanyoung** [comment]
> Thanks for the PR @seanyoung. Were you able to test the docker changes?

I haven't tested it, I was hoping CI would that for me.

> I am trying to test that at least the docker install works, but it's stuck waiting, not sure if that's expected...it did trigger with the correct runner, but maybe it's stuck because it's on my fork [siladu/besu/actions/runs/8978675974/job/24659493468](https://github.com/siladu/besu/actions/runs/8978675974/job/24659493468)

Only github repos/organizations signed up to the [private beta](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/) will have them available, so it won't work on your fork.

Is there a way we can test this in hyperledger/besu?

**Comment by siladu** [comment]
> > Thanks for the PR @seanyoung. Were you able to test the docker changes?
> 
> I haven't tested it, I was hoping CI would do that for me.
> 
> > I am trying to test that at least the docker install works, but it's stuck waiting, not sure if that's expected...it did trigger with the correct runner, but maybe it's stuck because it's on my fork [siladu/besu/actions/runs/8978675974/job/24659493468](https://github.com/siladu/besu/actions/runs/8978675974/job/24659493468)
> 
> Only github repos/organizations signed up to the [private beta](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/) will have them available, so it won't work on your fork.
> 
> Is there a way we can test this in hyperledger/besu?

@seanyoung Short of creating your own personal runner for this PR to point to, I can't think of one. Will merge and revert if it doesn't work. Not a big deal if we miss some intermediate commits on the develop tag.

**Comment by siladu** [comment]
@seanyoung It did indeed fail: https://github.com/hyperledger/besu/actions/runs/9026355992/job/24803532413

**Comment by siladu** [comment]
PR to revert: https://github.com/hyperledger/besu/pull/7087

**Pull request merged**
