### PR TITLE
New Maintainer candidate: Edward Mack

### PR DESCRIPTION
**Pull request by shemnon**
I propose adding Edward Mack from Chainsafe Systems as a maintainer for Besu.

Edward has been instrumental to adding the support for Ethereum Classic
and their two testnets Kotti and Mordor. Since Classic support is not
strategic to ConsenSys or Web3Labs it is safe to say that without his
contribution and continued involvement Ethereum Classic support would
not have happened. Because Ethereum Classic has some ambitious changes
slated for the next year promoting Edward to Maintainer will further
secure future support for it in Hyperledger Besu.

Voting ends two weeks from today, 2am UTC on 2019-12-10
https://www.timeanddate.com/countdown/to?iso=20191210T02&p0=1440

For more information on this process see the Becoming a Maintainer
section in the MAINTAINERS.md file.

See https://github.com/hyperledger/besu/search?q=edwardmack&type=Commits for all commits where Edward Mack participated (based on DCO)

### CODE REVIEW

**Comment by EdJoJob** [comment]
At this point in time I only see 4 PR's authored by @edwardmack and accepted into the master branch ([see here](edwardmack))
What is the other "significant change" which has been accepted?

**Comment by shemnon** [comment]
It's hiding - https://github.com/hyperledger/besu/pull/201/commits

Ed authored it (the verbiage in the MAINTAINERS.md) but greg pushed it.  Check the individual commits in the PR and the signed-off-by line.

**Comment by NicolasMassart** [comment]
See https://github.com/hyperledger/besu/search?q=edwardmack&type=Commits for all his commits

**Comment by bobsummerwill** [comment]
@edwardmack has done a brilliant job on the ETC support.

The pull requests have been high-quality, easy to follow, well organized.   Edward has interacted well with the other maintainers, and produced a whole new feature in a way which marries in excellently with the existing code.

Total thumbs up from ETC Cooperative for this proposal.

**Comment by bobsummerwill** [comment]
Is the only thing holding this merge up the fact that branch is out of date with the base branch?

**Comment by shemnon** [comment]
No, two week window or absolute majority is what we are waiting for to merge.  It's in the MAINTAINERS.md

**Comment by bobsummerwill** [comment]
Thanks for the clarification, @shemnon.

**Comment by shemnon** [comment]
The Two week window has concluded.  There are more than 3 approvals (8>3) and no vetos.  So this motion is deemed to have passed.

**Pull request merged**
