### PR TITLE
fix: allow domain names with - in ethstats

### PR DESCRIPTION
**Pull request by roderik**
## PR description

Our ethstats is hosted on the following domain (example): consortium-netstats.settlemint.com
The NETSTATS_URL_REGEX allows domain names (hence \w and not \d) but only allows dots, letters and numbers.
So netstats.settlemint.com would work, and consortium.netstats.settlemint.com and 10.10.10.15, but not consortium-netstats.settlemint.com
Modified the NETSTATS_URL_REGEX to allow dashes

## Changelog

- [x] I thought about the changelog and included a [changelog update if required](https://wiki.hyperledger.org/display/BESU/Changelog).

### CODE REVIEW

**Comment by matkt** [comment]
Hi, thanks for your update. This patch looks good to me

You must add `signed-off` to all your commits to have a green pipeline. You can use the following commands `git commit --amend --signoff` and pushing with `git push --force` to get DCO to accept your patch.

**Comment by roderik** [comment]
@matkt done

**Review by matkt — CHANGES_REQUESTED** [review]
Just one last thing. I think it would be nice to add a test to avoid future regression 

Maybe something like that here https://github.com/hyperledger/besu/blob/master/ethereum/ethstats/src/test/java/org/hyperledger/besu/ethstats/util/NetstatsUrlTest.java (not tested) 
```
@Test
  public void buildWithValidHost() {
    final String validHosts = new String []{"url-test.test.com", "url.test.com", "test.com", "10.10.10.15"};
    for (String host : validHosts){
        final NetstatsUrl netstatsUrl = NetstatsUrl.fromParams("Dev-Node-1:secret@"+host+":3001", CONTACT);
        assertThat(netstatsUrl.getHost()).isEqualTo(host);
    }
  }
```

**Comment by roderik** [comment]
@matkt ok, source formatting by hand and checking in the ci was less than fun :) (not doing java much so no decent setup on my end) but the test is in and passes.

**Review by matkt — APPROVED** [review]
LGTM

**Pull request merged**
